/** ISO 3166-1 alpha-2 to a representative point (country centre). Generated from the world-countries package (ODbL). Used to place order destinations on the globe at country level only. */
export const COUNTRY_POINTS: Record<string, { name: string; lon: number; lat: number }> = {
  AW: { name: "Aruba", lon: -70, lat: 12.5 },
  AF: { name: "Afghanistan", lon: 65, lat: 33 },
  AO: { name: "Angola", lon: 18.5, lat: -12.5 },
  AI: { name: "Anguilla", lon: -63.2, lat: 18.3 },
  AX: { name: "Åland Islands", lon: 19.9, lat: 60.1 },
  AL: { name: "Albania", lon: 20, lat: 41 },
  AD: { name: "Andorra", lon: 1.5, lat: 42.5 },
  AE: { name: "United Arab Emirates", lon: 54, lat: 24 },
  AR: { name: "Argentina", lon: -64, lat: -34 },
  AM: { name: "Armenia", lon: 45, lat: 40 },
  AS: { name: "American Samoa", lon: -170, lat: -14.3 },
  AQ: { name: "Antarctica", lon: 0, lat: -90 },
  TF: { name: "French Southern and Antarctic Lands", lon: 69.2, lat: -49.2 },
  AG: { name: "Antigua and Barbuda", lon: -61.8, lat: 17.1 },
  AU: { name: "Australia", lon: 133, lat: -27 },
  AT: { name: "Austria", lon: 13.3, lat: 47.3 },
  AZ: { name: "Azerbaijan", lon: 47.5, lat: 40.5 },
  BI: { name: "Burundi", lon: 30, lat: -3.5 },
  BE: { name: "Belgium", lon: 4, lat: 50.8 },
  BJ: { name: "Benin", lon: 2.3, lat: 9.5 },
  BF: { name: "Burkina Faso", lon: -2, lat: 13 },
  BD: { name: "Bangladesh", lon: 90, lat: 24 },
  BG: { name: "Bulgaria", lon: 25, lat: 43 },
  BH: { name: "Bahrain", lon: 50.6, lat: 26 },
  BS: { name: "Bahamas", lon: -76, lat: 24.3 },
  BA: { name: "Bosnia and Herzegovina", lon: 18, lat: 44 },
  BL: { name: "Saint Barthélemy", lon: -63.4, lat: 18.5 },
  SH: { name: "Saint Helena, Ascension and Tristan da Cunha", lon: -5.7, lat: -15.9 },
  BY: { name: "Belarus", lon: 28, lat: 53 },
  BZ: { name: "Belize", lon: -88.7, lat: 17.3 },
  BM: { name: "Bermuda", lon: -64.7, lat: 32.3 },
  BO: { name: "Bolivia", lon: -65, lat: -17 },
  BQ: { name: "Caribbean Netherlands", lon: -68.2, lat: 12.2 },
  BR: { name: "Brazil", lon: -55, lat: -10 },
  BB: { name: "Barbados", lon: -59.5, lat: 13.2 },
  BN: { name: "Brunei", lon: 114.7, lat: 4.5 },
  BT: { name: "Bhutan", lon: 90.5, lat: 27.5 },
  BV: { name: "Bouvet Island", lon: 3.4, lat: -54.4 },
  BW: { name: "Botswana", lon: 24, lat: -22 },
  CF: { name: "Central African Republic", lon: 21, lat: 7 },
  CA: { name: "Canada", lon: -95, lat: 60 },
  CC: { name: "Cocos (Keeling) Islands", lon: 96.8, lat: -12.5 },
  CH: { name: "Switzerland", lon: 8, lat: 47 },
  CL: { name: "Chile", lon: -71, lat: -30 },
  CN: { name: "China", lon: 105, lat: 35 },
  CI: { name: "Ivory Coast", lon: -5, lat: 8 },
  CM: { name: "Cameroon", lon: 12, lat: 6 },
  CD: { name: "DR Congo", lon: 25, lat: 0 },
  CG: { name: "Republic of the Congo", lon: 15, lat: -1 },
  CK: { name: "Cook Islands", lon: -159.8, lat: -21.2 },
  CO: { name: "Colombia", lon: -72, lat: 4 },
  KM: { name: "Comoros", lon: 44.3, lat: -12.2 },
  CV: { name: "Cape Verde", lon: -24, lat: 16 },
  CR: { name: "Costa Rica", lon: -84, lat: 10 },
  CU: { name: "Cuba", lon: -80, lat: 21.5 },
  CW: { name: "Curaçao", lon: -68.9, lat: 12.1 },
  CX: { name: "Christmas Island", lon: 105.7, lat: -10.5 },
  KY: { name: "Cayman Islands", lon: -80.5, lat: 19.5 },
  CY: { name: "Cyprus", lon: 33, lat: 35 },
  CZ: { name: "Czechia", lon: 15.5, lat: 49.8 },
  DE: { name: "Germany", lon: 9, lat: 51 },
  DJ: { name: "Djibouti", lon: 43, lat: 11.5 },
  DM: { name: "Dominica", lon: -61.3, lat: 15.4 },
  DK: { name: "Denmark", lon: 10, lat: 56 },
  DO: { name: "Dominican Republic", lon: -70.7, lat: 19 },
  DZ: { name: "Algeria", lon: 3, lat: 28 },
  EC: { name: "Ecuador", lon: -77.5, lat: -2 },
  EG: { name: "Egypt", lon: 30, lat: 27 },
  ER: { name: "Eritrea", lon: 39, lat: 15 },
  EH: { name: "Western Sahara", lon: -13, lat: 24.5 },
  ES: { name: "Spain", lon: -4, lat: 40 },
  EE: { name: "Estonia", lon: 26, lat: 59 },
  ET: { name: "Ethiopia", lon: 38, lat: 8 },
  FI: { name: "Finland", lon: 26, lat: 64 },
  FJ: { name: "Fiji", lon: 175, lat: -18 },
  FK: { name: "Falkland Islands", lon: -59, lat: -51.7 },
  FR: { name: "France", lon: 2, lat: 46 },
  FO: { name: "Faroe Islands", lon: -7, lat: 62 },
  FM: { name: "Micronesia", lon: 158.3, lat: 6.9 },
  GA: { name: "Gabon", lon: 11.8, lat: -1 },
  GB: { name: "United Kingdom", lon: -2, lat: 54 },
  GE: { name: "Georgia", lon: 43.5, lat: 42 },
  GG: { name: "Guernsey", lon: -2.6, lat: 49.5 },
  GH: { name: "Ghana", lon: -2, lat: 8 },
  GI: { name: "Gibraltar", lon: -5.3, lat: 36.1 },
  GN: { name: "Guinea", lon: -10, lat: 11 },
  GP: { name: "Guadeloupe", lon: -61.6, lat: 16.3 },
  GM: { name: "Gambia", lon: -16.6, lat: 13.5 },
  GW: { name: "Guinea-Bissau", lon: -15, lat: 12 },
  GQ: { name: "Equatorial Guinea", lon: 10, lat: 2 },
  GR: { name: "Greece", lon: 22, lat: 39 },
  GD: { name: "Grenada", lon: -61.7, lat: 12.1 },
  GL: { name: "Greenland", lon: -40, lat: 72 },
  GT: { name: "Guatemala", lon: -90.2, lat: 15.5 },
  GF: { name: "French Guiana", lon: -53, lat: 4 },
  GU: { name: "Guam", lon: 144.8, lat: 13.5 },
  GY: { name: "Guyana", lon: -59, lat: 5 },
  HK: { name: "Hong Kong", lon: 114.2, lat: 22.3 },
  HM: { name: "Heard Island and McDonald Islands", lon: 72.5, lat: -53.1 },
  HN: { name: "Honduras", lon: -86.5, lat: 15 },
  HR: { name: "Croatia", lon: 15.5, lat: 45.2 },
  HT: { name: "Haiti", lon: -72.4, lat: 19 },
  HU: { name: "Hungary", lon: 20, lat: 47 },
  ID: { name: "Indonesia", lon: 120, lat: -5 },
  IM: { name: "Isle of Man", lon: -4.5, lat: 54.3 },
  IN: { name: "India", lon: 77, lat: 20 },
  IO: { name: "British Indian Ocean Territory", lon: 71.5, lat: -6 },
  IE: { name: "Ireland", lon: -8, lat: 53 },
  IR: { name: "Iran", lon: 53, lat: 32 },
  IQ: { name: "Iraq", lon: 44, lat: 33 },
  IS: { name: "Iceland", lon: -18, lat: 65 },
  IL: { name: "Israel", lon: 35.1, lat: 31.5 },
  IT: { name: "Italy", lon: 12.8, lat: 42.8 },
  JM: { name: "Jamaica", lon: -77.5, lat: 18.3 },
  JE: { name: "Jersey", lon: -2.2, lat: 49.3 },
  JO: { name: "Jordan", lon: 36, lat: 31 },
  JP: { name: "Japan", lon: 138, lat: 36 },
  KZ: { name: "Kazakhstan", lon: 68, lat: 48 },
  KE: { name: "Kenya", lon: 38, lat: 1 },
  KG: { name: "Kyrgyzstan", lon: 75, lat: 41 },
  KH: { name: "Cambodia", lon: 105, lat: 13 },
  KI: { name: "Kiribati", lon: 173, lat: 1.4 },
  KN: { name: "Saint Kitts and Nevis", lon: -62.7, lat: 17.3 },
  KR: { name: "South Korea", lon: 127.5, lat: 37 },
  XK: { name: "Kosovo", lon: 21.2, lat: 42.7 },
  KW: { name: "Kuwait", lon: 45.8, lat: 29.5 },
  LA: { name: "Laos", lon: 105, lat: 18 },
  LB: { name: "Lebanon", lon: 35.8, lat: 33.8 },
  LR: { name: "Liberia", lon: -9.5, lat: 6.5 },
  LY: { name: "Libya", lon: 17, lat: 25 },
  LC: { name: "Saint Lucia", lon: -61, lat: 13.9 },
  LI: { name: "Liechtenstein", lon: 9.5, lat: 47.3 },
  LK: { name: "Sri Lanka", lon: 81, lat: 7 },
  LS: { name: "Lesotho", lon: 28.5, lat: -29.5 },
  LT: { name: "Lithuania", lon: 24, lat: 56 },
  LU: { name: "Luxembourg", lon: 6.2, lat: 49.8 },
  LV: { name: "Latvia", lon: 25, lat: 57 },
  MO: { name: "Macau", lon: 113.6, lat: 22.2 },
  MF: { name: "Saint Martin", lon: -63.9, lat: 18.1 },
  MA: { name: "Morocco", lon: -5, lat: 32 },
  MC: { name: "Monaco", lon: 7.4, lat: 43.7 },
  MD: { name: "Moldova", lon: 29, lat: 47 },
  MG: { name: "Madagascar", lon: 47, lat: -20 },
  MV: { name: "Maldives", lon: 73, lat: 3.3 },
  MX: { name: "Mexico", lon: -102, lat: 23 },
  MH: { name: "Marshall Islands", lon: 168, lat: 9 },
  MK: { name: "North Macedonia", lon: 22, lat: 41.8 },
  ML: { name: "Mali", lon: -4, lat: 17 },
  MT: { name: "Malta", lon: 14.6, lat: 35.8 },
  MM: { name: "Myanmar", lon: 98, lat: 22 },
  ME: { name: "Montenegro", lon: 19.3, lat: 42.5 },
  MN: { name: "Mongolia", lon: 105, lat: 46 },
  MP: { name: "Northern Mariana Islands", lon: 145.8, lat: 15.2 },
  MZ: { name: "Mozambique", lon: 35, lat: -18.2 },
  MR: { name: "Mauritania", lon: -12, lat: 20 },
  MS: { name: "Montserrat", lon: -62.2, lat: 16.8 },
  MQ: { name: "Martinique", lon: -61, lat: 14.7 },
  MU: { name: "Mauritius", lon: 57.6, lat: -20.3 },
  MW: { name: "Malawi", lon: 34, lat: -13.5 },
  MY: { name: "Malaysia", lon: 112.5, lat: 2.5 },
  YT: { name: "Mayotte", lon: 45.2, lat: -12.8 },
  NA: { name: "Namibia", lon: 17, lat: -22 },
  NC: { name: "New Caledonia", lon: 165.5, lat: -21.5 },
  NE: { name: "Niger", lon: 8, lat: 16 },
  NF: { name: "Norfolk Island", lon: 168, lat: -29 },
  NG: { name: "Nigeria", lon: 8, lat: 10 },
  NI: { name: "Nicaragua", lon: -85, lat: 13 },
  NU: { name: "Niue", lon: -169.9, lat: -19 },
  NL: { name: "Netherlands", lon: 5.8, lat: 52.5 },
  NO: { name: "Norway", lon: 10, lat: 62 },
  NP: { name: "Nepal", lon: 84, lat: 28 },
  NR: { name: "Nauru", lon: 166.9, lat: -0.5 },
  NZ: { name: "New Zealand", lon: 174, lat: -41 },
  OM: { name: "Oman", lon: 57, lat: 21 },
  PK: { name: "Pakistan", lon: 70, lat: 30 },
  PA: { name: "Panama", lon: -80, lat: 9 },
  PN: { name: "Pitcairn Islands", lon: -130.1, lat: -25.1 },
  PE: { name: "Peru", lon: -76, lat: -10 },
  PH: { name: "Philippines", lon: 122, lat: 13 },
  PW: { name: "Palau", lon: 134.5, lat: 7.5 },
  PG: { name: "Papua New Guinea", lon: 147, lat: -6 },
  PL: { name: "Poland", lon: 20, lat: 52 },
  PR: { name: "Puerto Rico", lon: -66.5, lat: 18.3 },
  KP: { name: "North Korea", lon: 127, lat: 40 },
  PT: { name: "Portugal", lon: -8, lat: 39.5 },
  PY: { name: "Paraguay", lon: -58, lat: -23 },
  PS: { name: "Palestine", lon: 35.2, lat: 31.9 },
  PF: { name: "French Polynesia", lon: -140, lat: -15 },
  QA: { name: "Qatar", lon: 51.3, lat: 25.5 },
  RE: { name: "Réunion", lon: 55.5, lat: -21.1 },
  RO: { name: "Romania", lon: 25, lat: 46 },
  RU: { name: "Russia", lon: 100, lat: 60 },
  RW: { name: "Rwanda", lon: 30, lat: -2 },
  SA: { name: "Saudi Arabia", lon: 45, lat: 25 },
  SD: { name: "Sudan", lon: 30, lat: 15 },
  SN: { name: "Senegal", lon: -14, lat: 14 },
  SG: { name: "Singapore", lon: 103.8, lat: 1.4 },
  GS: { name: "South Georgia", lon: -37, lat: -54.5 },
  SJ: { name: "Svalbard and Jan Mayen", lon: 20, lat: 78 },
  SB: { name: "Solomon Islands", lon: 159, lat: -8 },
  SL: { name: "Sierra Leone", lon: -11.5, lat: 8.5 },
  SV: { name: "El Salvador", lon: -88.9, lat: 13.8 },
  SM: { name: "San Marino", lon: 12.4, lat: 43.8 },
  SO: { name: "Somalia", lon: 49, lat: 10 },
  PM: { name: "Saint Pierre and Miquelon", lon: -56.3, lat: 46.8 },
  RS: { name: "Serbia", lon: 21, lat: 44 },
  SS: { name: "South Sudan", lon: 30, lat: 7 },
  ST: { name: "São Tomé and Príncipe", lon: 7, lat: 1 },
  SR: { name: "Suriname", lon: -56, lat: 4 },
  SK: { name: "Slovakia", lon: 19.5, lat: 48.7 },
  SI: { name: "Slovenia", lon: 14.8, lat: 46.1 },
  SE: { name: "Sweden", lon: 15, lat: 62 },
  SZ: { name: "Eswatini", lon: 31.5, lat: -26.5 },
  SX: { name: "Sint Maarten", lon: -63, lat: 18 },
  SC: { name: "Seychelles", lon: 55.7, lat: -4.6 },
  SY: { name: "Syria", lon: 38, lat: 35 },
  TC: { name: "Turks and Caicos Islands", lon: -71.6, lat: 21.8 },
  TD: { name: "Chad", lon: 19, lat: 15 },
  TG: { name: "Togo", lon: 1.2, lat: 8 },
  TH: { name: "Thailand", lon: 100, lat: 15 },
  TJ: { name: "Tajikistan", lon: 71, lat: 39 },
  TK: { name: "Tokelau", lon: -172, lat: -9 },
  TM: { name: "Turkmenistan", lon: 60, lat: 40 },
  TL: { name: "Timor-Leste", lon: 125.9, lat: -8.8 },
  TO: { name: "Tonga", lon: -175, lat: -20 },
  TT: { name: "Trinidad and Tobago", lon: -61, lat: 11 },
  TN: { name: "Tunisia", lon: 9, lat: 34 },
  TR: { name: "Türkiye", lon: 35, lat: 39 },
  TV: { name: "Tuvalu", lon: 178, lat: -8 },
  TW: { name: "Taiwan", lon: 121, lat: 23.5 },
  TZ: { name: "Tanzania", lon: 35, lat: -6 },
  UG: { name: "Uganda", lon: 32, lat: 1 },
  UA: { name: "Ukraine", lon: 32, lat: 49 },
  UM: { name: "United States Minor Outlying Islands", lon: 166.6, lat: 19.3 },
  UY: { name: "Uruguay", lon: -56, lat: -33 },
  US: { name: "United States", lon: -97, lat: 38 },
  UZ: { name: "Uzbekistan", lon: 64, lat: 41 },
  VA: { name: "Vatican City", lon: 12.5, lat: 41.9 },
  VC: { name: "Saint Vincent and the Grenadines", lon: -61.2, lat: 13.3 },
  VE: { name: "Venezuela", lon: -66, lat: 8 },
  VG: { name: "British Virgin Islands", lon: -64.6, lat: 18.4 },
  VI: { name: "United States Virgin Islands", lon: -64.9, lat: 18.4 },
  VN: { name: "Vietnam", lon: 107.8, lat: 16.2 },
  VU: { name: "Vanuatu", lon: 167, lat: -16 },
  WF: { name: "Wallis and Futuna", lon: -176.2, lat: -13.3 },
  WS: { name: "Samoa", lon: -172.3, lat: -13.6 },
  YE: { name: "Yemen", lon: 48, lat: 15 },
  ZA: { name: "South Africa", lon: 24, lat: -29 },
  ZM: { name: "Zambia", lon: 30, lat: -15 },
  ZW: { name: "Zimbabwe", lon: 30, lat: -20 },
};
