import type { ProductCategory } from "@/lib/domains/catalog/publish";
import type { VisualIntakeAnalyzer } from "./intake-types";
import type { ProductDraftGenerator, ProductDraftOutput } from "./types";

function slugFromPrompt(prompt: string): string {
  return prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join(" ");
}

function inferCategory(prompt: string): ProductCategory {
  const text = prompt.toLowerCase();

  if (text.includes("baby") || text.includes("toddler") || text.includes("nursery")) {
    return "baby_me";
  }

  if (text.includes("toy") || text.includes("sensory") || text.includes("fidget")) {
    return "toys_sensory";
  }

  if (text.includes("original") || text.includes("olo")) {
    return "originals";
  }

  return "sweetoh_creations";
}

function buildMockDraft(prompt: string): ProductDraftOutput {
  const category = inferCategory(prompt);
  const label = slugFromPrompt(prompt) || "mock product";
  const title =
    label.charAt(0).toUpperCase() + label.slice(1) + " (Mock AI Draft)";

  return {
    title,
    description: `Mock AI draft for: ${prompt}. Replace with real OpenAI output in production testing.`,
    shortDescription: `Mock listing — ${label}.`,
    seoTitle: title.slice(0, 60),
    seoDescription: `Shop ${label} from Island Sprouts. Mock draft for E2E testing.`.slice(
      0,
      160,
    ),
    category,
    suggestedTags: ["mock", "ai-draft", category.replaceAll("_", "-")],
    suggestedCollections:
      category === "sweetoh_creations"
        ? ["Sweet'Oh Creations"]
        : category === "baby_me"
          ? ["Baby + Me"]
          : ["Toys & Sensory"],
    suggestedPriceCents: category === "sweetoh_creations" ? 2499 : 1999,
    internalNotes:
      "Generated by AI_MOCK_MODE for local E2E testing. Review all fields before publish.",
  };
}

export const generateProductDraftMock: ProductDraftGenerator = async (input) => {
  const output = buildMockDraft(input.prompt.trim() || "generic product");

  return {
    output,
    rawResponse: { provider: "mock", mode: "text_prompt", prompt: input.prompt },
  };
};

export const analyzeProductImageMock: VisualIntakeAnalyzer = async (input) => {
  const prompt =
    input.operatorNotes?.trim() ||
    "uploaded product photo mock intake";
  const output = buildMockDraft(prompt);

  return {
    output: {
      ...output,
      confidenceScore: 82,
      detection: {
        productType: "apparel",
        colors: ["tropical blue", "coral"],
        materials: ["cotton"],
        dimensions: "12mo",
        variants: ["toddler tee"],
      },
    },
    rawResponse: {
      provider: "mock",
      mode: input.inputMode ?? "image_only",
      mimeType: input.mimeType,
    },
  };
};
