import type { ProductCategory } from "@/lib/domains/catalog/publish";
import { categoryLabel } from "@/lib/domains/catalog/categories";
import type { VisualIntakeAnalyzer } from "./intake-types";
import type { ProductDraftGenerator, ProductDraftOutput } from "./types";

function slugFromPrompt(prompt: string): string {
  return prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join(" ");
}

function inferCategory(prompt: string): ProductCategory {
  const text = prompt.toLowerCase();

  if (
    text.includes("baby") ||
    text.includes("toddler") ||
    text.includes("kids") ||
    text.includes("youth") ||
    text.includes("onesie")
  ) {
    return "kids";
  }

  if (
    text.includes("mug") ||
    text.includes("tumbler") ||
    text.includes("cup") ||
    text.includes("drink")
  ) {
    return "drinkware";
  }

  if (
    text.includes("blanket") ||
    text.includes("pillow") ||
    text.includes("poster") ||
    text.includes("home")
  ) {
    return "home";
  }

  if (
    text.includes("tote") ||
    text.includes("hat") ||
    text.includes("sticker") ||
    text.includes("bag")
  ) {
    return "accessories";
  }

  if (
    text.includes("tee") ||
    text.includes("hoodie") ||
    text.includes("shirt") ||
    text.includes("apparel")
  ) {
    return "apparel";
  }

  return "custom";
}

function buildMockDraft(prompt: string): ProductDraftOutput {
  const category = inferCategory(prompt);
  const label = slugFromPrompt(prompt) || "mock product";
  const title =
    label.charAt(0).toUpperCase() + label.slice(1) + " (Mock AI Draft)";
  const aisle = categoryLabel(category);

  return {
    title,
    description: `Mock AI draft for: ${prompt}. Replace with real OpenAI output in production testing.`,
    shortDescription: `Mock listing — ${label}.`,
    seoTitle: title.slice(0, 60),
    seoDescription: `Shop ${label} from Sweet'Oh. Mock draft for E2E testing.`.slice(
      0,
      160,
    ),
    category,
    suggestedTags: ["mock", "ai-draft", category],
    suggestedCollections: [aisle],
    suggestedPriceCents: category === "custom" ? 2499 : 1999,
    internalNotes:
      "Generated by AI_MOCK_MODE for local E2E testing. Review all fields before publish.",
  };
}

export const generateProductDraftMock: ProductDraftGenerator = async (input) => {
  const output = buildMockDraft(input.prompt.trim() || "generic product");

  return {
    output,
    rawResponse: { provider: "mock", mode: "text_prompt", prompt: input.prompt },
  };
};

export const analyzeProductImageMock: VisualIntakeAnalyzer = async (input) => {
  const prompt =
    input.operatorNotes?.trim() ||
    "uploaded product photo mock intake";
  const output = buildMockDraft(prompt);

  return {
    output: {
      ...output,
      confidenceScore: 82,
      detection: {
        productType: "Pro Club heavyweight toddler tee",
        colors: ["tropical blue", "coral"],
        materials: ["heavyweight cotton"],
        dimensions: "12mo",
        variants: ["toddler tee"],
      },
    },
    rawResponse: {
      provider: "mock",
      mode: input.inputMode ?? "image_only",
      mimeType: input.mimeType,
    },
  };
};
