"use client";

import { useEffect, useMemo, useState } from "react";
import { PRODUCT_FONTS } from "@/lib/studio/fonts";
import { STUDIO_FONT_PROVENANCE } from "@/lib/studio/font-provenance";
import { STUDIO_ASSETS, studioAssetUrl } from "@/lib/studio/asset-library";

const FAVORITES_KEY = "sweetoh:studio:favorites:v1";
const RECENTS_KEY = "sweetoh:studio:recent:v1";
type Filter = "All" | "Nature" | "Accents" | "Frames" | "Patterns" | "Fonts" | "Favorites" | "Recent";
const FILTERS: Filter[] = ["All", "Nature", "Accents", "Frames", "Patterns", "Fonts", "Favorites", "Recent"];

function readIds(key: string): string[] {
  try {
    const value: unknown = JSON.parse(localStorage.getItem(key) ?? "[]");
    return Array.isArray(value) ? value.filter((id): id is string => typeof id === "string").slice(0, 50) : [];
  } catch { return []; }
}

export function AssetLibraryPanel({ disabled, onAddGraphic, onAddFont }: {
  disabled: boolean;
  onAddGraphic: (id: string) => void;
  onAddFont: (key: string) => void;
}) {
  const [filter, setFilter] = useState<Filter>("All");
  const [query, setQuery] = useState("");
  const [favorites, setFavorites] = useState<string[]>([]);
  const [recent, setRecent] = useState<string[]>([]);
  useEffect(() => {
    const sync = () => { setFavorites(readIds(FAVORITES_KEY)); setRecent(readIds(RECENTS_KEY)); };
    queueMicrotask(sync);
    window.addEventListener("storage", sync);
    return () => window.removeEventListener("storage", sync);
  }, []);

  const entries = useMemo(() => [
    ...STUDIO_ASSETS.map((asset) => ({ id: asset.id, name: asset.name, category: asset.category, tags: asset.tags.join(" "), kind: asset.kind, preview: studioAssetUrl(asset), font: null as string | null, license: asset.license })),
    ...PRODUCT_FONTS.map((font) => ({ id: `font:${font.key}`, name: font.label, category: "Fonts", tags: "text typography lettering", kind: "font", preview: "", font: font.family as string | null, license: STUDIO_FONT_PROVENANCE[font.key].license })),
  ], []);
  const visible = entries.filter((entry) => {
    if (filter === "Favorites" && !favorites.includes(entry.id)) return false;
    if (filter === "Recent" && !recent.includes(entry.id)) return false;
    if (!["All", "Favorites", "Recent"].includes(filter) && entry.category !== filter) return false;
    const needle = query.trim().toLowerCase();
    return !needle || `${entry.name} ${entry.category} ${entry.tags}`.toLowerCase().includes(needle);
  }).sort((a, b) => filter === "Recent" ? recent.indexOf(a.id) - recent.indexOf(b.id) : a.name.localeCompare(b.name));

  function use(id: string) {
    const next = [id, ...recent.filter((value) => value !== id)].slice(0, 24);
    setRecent(next);
    localStorage.setItem(RECENTS_KEY, JSON.stringify(next));
    if (id.startsWith("font:")) onAddFont(id.slice(5));
    else onAddGraphic(id);
  }
  function favorite(id: string) {
    const next = favorites.includes(id) ? favorites.filter((value) => value !== id) : [...favorites, id];
    setFavorites(next);
    localStorage.setItem(FAVORITES_KEY, JSON.stringify(next));
  }

  return <div className="pe-panel-body pe-asset-library">
    <label className="sr-only" htmlFor="studio-asset-search">Search Studio assets</label>
    <input id="studio-asset-search" className="pe-search" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search elements and fonts" />
    <div className="pe-asset-filters" aria-label="Asset categories">{FILTERS.map((item) => <button key={item} type="button" aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div>
    <p className="pe-muted pe-small">Original SweetOh graphics and open-license fonts. Add, then resize, rotate, layer and print.</p>
    {visible.length ? <div className="pe-asset-grid">{visible.map((entry) => <div key={entry.id} className="pe-asset-card">
      <button type="button" disabled={disabled} onClick={() => use(entry.id)} aria-label={`Add ${entry.name}`}>
        {entry.font ? <span className="pe-asset-font" style={{ fontFamily: entry.font }}>Aa</span> : (
          // The preview is a tiny inlined SVG generated by this registry.
          // eslint-disable-next-line @next/next/no-img-element
          <img src={entry.preview} alt="" />
        )}
        <span>{entry.name}</span>
      </button>
      <button type="button" className="pe-asset-favorite" onClick={() => favorite(entry.id)} aria-label={`${favorites.includes(entry.id) ? "Remove" : "Add"} ${entry.name} ${favorites.includes(entry.id) ? "from" : "to"} favorites`} aria-pressed={favorites.includes(entry.id)}>★</button>
      <small title={entry.license}>{entry.kind === "font" ? entry.license.startsWith("Apache") ? "Apache 2.0" : "OFL" : "Original"}</small>
    </div>)}</div> : <p className="pe-muted">No matching assets.</p>}
  </div>;
}
