import { writeFile } from "node:fs/promises";
import { STUDIO_ASSETS } from "../lib/studio/asset-library";
import { canSurfaceStudioAsset } from "../lib/studio/asset-library-search";

const metadata = STUDIO_ASSETS.map((asset) => {
  const { svg: _svg, ...fields } = asset;
  return { ...fields, studioUseApproved: canSurfaceStudioAsset(asset) };
});
const output = new URL("../lib/studio/asset-manifest.ts", import.meta.url);
async function main() {
  await writeFile(output, `/** Generated by scripts/build-studio-asset-manifest.ts. Keep SVG artwork in server-only asset packs. */\nimport type { StudioAssetMetadata } from "./asset-library-client";\n\nexport const STUDIO_ASSET_MANIFEST = JSON.parse(${JSON.stringify(JSON.stringify(metadata))}) as readonly StudioAssetMetadata[];\n`);
  console.log(`Wrote ${metadata.length} metadata entries to ${output.pathname}`);
}
void main();
