/** Generated from CC0 East/Central Asian textile photographs (National Museum of World Cultures, Netherlands, via Europeana). Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const EAST_ASIAN_TEXTILES_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "east-asian-textile-manchu-dragon-robe-v1",
    "name": "Manchu dragon robe (Qing dynasty style, blue silk with gold embroidery)",
    "kind": "element",
    "category": "Illustrations",
    "tags": [
      "dragon robe",
      "Manchu",
      "Qing dynasty",
      "Chinese textile",
      "silk embroidery",
      "dragon motif",
      "historical costume",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_760029",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-3159-4.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Manchu dragon robe (Qing dynasty style, blue silk with gold embroidery). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/east-asian-textiles/manchu-dragon-robe.webp",
    "width": 2400,
    "height": 1588
  },
  {
    "id": "east-asian-textile-gold-thread-shoulder-cloth-v1",
    "name": "Shoulder cloth with typical Chinese embroidery of gold thread",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ikat-style weave",
      "paisley border",
      "gold thread embroidery",
      "shoulder cloth",
      "Chinese textile",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_599979",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/300-325.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Shoulder cloth with typical Chinese embroidery of gold thread. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/east-asian-textiles/gold-thread-shoulder-cloth.webp",
    "width": 707,
    "height": 1000
  },
  {
    "id": "east-asian-textile-brocade-jacket-v1",
    "name": "Red silk brocade jacket with gold star motifs",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "brocade",
      "silk",
      "star motif",
      "floral pattern",
      "Chinese textile",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_656345",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-370-2871.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Red silk brocade jacket with gold star motifs. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/east-asian-textiles/brocade-jacket.webp",
    "width": 2400,
    "height": 1076
  }
];
