/** Generated from bundled MIT-licensed Feather Icons originals. Stroke color is left as currentColor so Studio's layer color controls apply. */
import type { StudioAsset } from "./asset-library";

export const FEATHER_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "feather-award-v1",
    "name": "Award ribbon",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "award",
      "medal",
      "achievement",
      "graduation",
      "recognition",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/award.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"8\" r=\"7\"/><polyline points=\"8.21 13.89 7 23 12 20 17 23 15.79 13.88\"/></svg>"
  },
  {
    "id": "feather-book-open-v1",
    "name": "Open book",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "book",
      "reading",
      "education",
      "library",
      "teacher gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/book-open.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z\"/><path d=\"M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z\"/></svg>"
  },
  {
    "id": "feather-clock-v1",
    "name": "Clock",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "clock",
      "time",
      "retirement",
      "anniversary",
      "watch",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/clock.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><polyline points=\"12 6 12 12 16 14\"/></svg>"
  },
  {
    "id": "feather-cloud-drizzle-v1",
    "name": "Cloud with drizzle",
    "kind": "element",
    "category": "Nature & Weather",
    "tags": [
      "weather",
      "drizzle",
      "rain",
      "cloud",
      "forecast",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/cloud-drizzle.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"8\" y1=\"19\" x2=\"8\" y2=\"21\"/><line x1=\"8\" y1=\"13\" x2=\"8\" y2=\"15\"/><line x1=\"16\" y1=\"19\" x2=\"16\" y2=\"21\"/><line x1=\"16\" y1=\"13\" x2=\"16\" y2=\"15\"/><line x1=\"12\" y1=\"21\" x2=\"12\" y2=\"23\"/><line x1=\"12\" y1=\"15\" x2=\"12\" y2=\"17\"/><path d=\"M20 16.58A5 5 0 0 0 18 7h-1.26A8 8 0 1 0 4 15.25\"/></svg>"
  },
  {
    "id": "feather-cloud-lightning-v1",
    "name": "Cloud with lightning",
    "kind": "element",
    "category": "Nature & Weather",
    "tags": [
      "weather",
      "storm",
      "lightning",
      "thunder",
      "cloud",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/cloud-lightning.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 16.9A5 5 0 0 0 18 7h-1.26a8 8 0 1 0-11.62 9\"/><polyline points=\"13 11 9 17 15 17 11 23\"/></svg>"
  },
  {
    "id": "feather-cloud-snow-v1",
    "name": "Cloud with snow",
    "kind": "element",
    "category": "Nature & Weather",
    "tags": [
      "weather",
      "snow",
      "winter",
      "cloud",
      "christmas",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/cloud-snow.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 17.58A5 5 0 0 0 18 8h-1.26A8 8 0 1 0 4 16.25\"/><line x1=\"8\" y1=\"16\" x2=\"8.01\" y2=\"16\"/><line x1=\"8\" y1=\"20\" x2=\"8.01\" y2=\"20\"/><line x1=\"12\" y1=\"18\" x2=\"12.01\" y2=\"18\"/><line x1=\"12\" y1=\"22\" x2=\"12.01\" y2=\"22\"/><line x1=\"16\" y1=\"16\" x2=\"16.01\" y2=\"16\"/><line x1=\"16\" y1=\"20\" x2=\"16.01\" y2=\"20\"/></svg>"
  },
  {
    "id": "feather-disc-v1",
    "name": "Vinyl record",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "music",
      "vinyl",
      "record",
      "dj",
      "retro",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/disc.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>"
  },
  {
    "id": "feather-dollar-sign-v1",
    "name": "Dollar sign",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "money",
      "finance",
      "business",
      "currency",
      "accountant gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/dollar-sign.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"12\" y1=\"1\" x2=\"12\" y2=\"23\"/><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"/></svg>"
  },
  {
    "id": "feather-droplet-v1",
    "name": "Water droplet",
    "kind": "element",
    "category": "Nature & Weather",
    "tags": [
      "water",
      "droplet",
      "rain",
      "ocean",
      "hydration",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/droplet.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z\"/></svg>"
  },
  {
    "id": "feather-film-v1",
    "name": "Film reel frame",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "film",
      "movie",
      "cinema",
      "videographer gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/film.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"2.18\" ry=\"2.18\"/><line x1=\"7\" y1=\"2\" x2=\"7\" y2=\"22\"/><line x1=\"17\" y1=\"2\" x2=\"17\" y2=\"22\"/><line x1=\"2\" y1=\"12\" x2=\"22\" y2=\"12\"/><line x1=\"2\" y1=\"7\" x2=\"7\" y2=\"7\"/><line x1=\"2\" y1=\"17\" x2=\"7\" y2=\"17\"/><line x1=\"17\" y1=\"17\" x2=\"22\" y2=\"17\"/><line x1=\"17\" y1=\"7\" x2=\"22\" y2=\"7\"/></svg>"
  },
  {
    "id": "feather-flag-v1",
    "name": "Flag",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "flag",
      "milestone",
      "goal",
      "sports",
      "marker",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/flag.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z\"/><line x1=\"4\" y1=\"22\" x2=\"4\" y2=\"15\"/></svg>"
  },
  {
    "id": "feather-globe-v1",
    "name": "Globe",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "globe",
      "world",
      "travel",
      "geography",
      "teacher gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/globe.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"2\" y1=\"12\" x2=\"22\" y2=\"12\"/><path d=\"M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z\"/></svg>"
  },
  {
    "id": "feather-headphones-v1",
    "name": "Headphones",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "headphones",
      "music",
      "audio",
      "dj gift",
      "gamer gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/headphones.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 18v-6a9 9 0 0 1 18 0v6\"/><path d=\"M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z\"/></svg>"
  },
  {
    "id": "feather-hexagon-v1",
    "name": "Hexagon frame",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "hexagon",
      "geometric",
      "badge",
      "frame",
      "monogram",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/hexagon.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"/></svg>"
  },
  {
    "id": "feather-home-v1",
    "name": "Home",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "home",
      "house",
      "housewarming",
      "family",
      "real estate gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/home.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/><polyline points=\"9 22 9 12 15 12 15 22\"/></svg>"
  },
  {
    "id": "feather-key-v1",
    "name": "Key",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "key",
      "new home",
      "unlock",
      "realtor gift",
      "graduation",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/key.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4\"/></svg>"
  },
  {
    "id": "feather-life-buoy-v1",
    "name": "Life buoy",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "nautical",
      "life buoy",
      "ocean",
      "coastal",
      "boating",
      "sailor gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/life-buoy.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><line x1=\"4.93\" y1=\"4.93\" x2=\"9.17\" y2=\"9.17\"/><line x1=\"14.83\" y1=\"14.83\" x2=\"19.07\" y2=\"19.07\"/><line x1=\"14.83\" y1=\"9.17\" x2=\"19.07\" y2=\"4.93\"/><line x1=\"14.83\" y1=\"9.17\" x2=\"18.36\" y2=\"5.64\"/><line x1=\"4.93\" y1=\"19.07\" x2=\"9.17\" y2=\"14.83\"/></svg>"
  },
  {
    "id": "feather-lock-v1",
    "name": "Padlock",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "lock",
      "security",
      "privacy",
      "safety",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/lock.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/></svg>"
  },
  {
    "id": "feather-map-v1",
    "name": "Folded map",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "map",
      "travel",
      "adventure",
      "explorer gift",
      "hiking",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/map.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6\"/><line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"18\"/><line x1=\"16\" y1=\"6\" x2=\"16\" y2=\"22\"/></svg>"
  },
  {
    "id": "feather-map-pin-v1",
    "name": "Map pin",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "map pin",
      "location",
      "travel",
      "hometown",
      "wedding location",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/map-pin.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"/><circle cx=\"12\" cy=\"10\" r=\"3\"/></svg>"
  },
  {
    "id": "feather-mic-v1",
    "name": "Microphone",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "microphone",
      "singer gift",
      "podcast",
      "karaoke",
      "speaker gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/mic.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z\"/><path d=\"M19 10v2a7 7 0 0 1-14 0v-2\"/><line x1=\"12\" y1=\"19\" x2=\"12\" y2=\"23\"/><line x1=\"8\" y1=\"23\" x2=\"16\" y2=\"23\"/></svg>"
  },
  {
    "id": "feather-moon-v1",
    "name": "Crescent moon",
    "kind": "element",
    "category": "Nature & Weather",
    "tags": [
      "moon",
      "crescent",
      "night",
      "celestial",
      "dreamy",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/moon.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z\"/></svg>"
  },
  {
    "id": "feather-octagon-v1",
    "name": "Octagon frame",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "octagon",
      "geometric",
      "badge",
      "frame",
      "stop sign shape",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/octagon.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2\"/></svg>"
  },
  {
    "id": "feather-package-v1",
    "name": "Shipping package",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "package",
      "shipping",
      "delivery",
      "small business",
      "mail carrier gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/package.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"16.5\" y1=\"9.4\" x2=\"7.5\" y2=\"4.21\"/><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"/><polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"/><line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"/></svg>"
  },
  {
    "id": "feather-pen-tool-v1",
    "name": "Pen nib",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "pen",
      "writer gift",
      "calligraphy",
      "artist",
      "signature",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/pen-tool.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg width=\"200\" height=\"200\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 19l7-7 3 3-7 7-3-3z\"/><path d=\"M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z\"/><path d=\"M2 2l7.586 7.586\"/><circle cx=\"11\" cy=\"11\" r=\"2\"/></svg>"
  },
  {
    "id": "feather-phone-v1",
    "name": "Phone",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "phone",
      "call",
      "contact",
      "business card",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/phone.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\"/></svg>"
  },
  {
    "id": "feather-printer-v1",
    "name": "Printer",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "printer",
      "print shop",
      "office",
      "small business",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/printer.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"6 9 6 2 18 2 18 9\"/><path d=\"M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2\"/><rect x=\"6\" y=\"14\" width=\"12\" height=\"8\"/></svg>"
  },
  {
    "id": "feather-radio-v1",
    "name": "Radio",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "radio",
      "retro",
      "broadcast",
      "music",
      "dj gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/radio.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"2\"/><path d=\"M16.24 7.76a6 6 0 0 1 0 8.49m-8.48-.01a6 6 0 0 1 0-8.49m11.31-2.82a10 10 0 0 1 0 14.14m-14.14 0a10 10 0 0 1 0-14.14\"/></svg>"
  },
  {
    "id": "feather-settings-v1",
    "name": "Gear",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "gear",
      "settings",
      "mechanic gift",
      "engineer gift",
      "tools",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/settings.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z\"/></svg>"
  },
  {
    "id": "feather-shield-v1",
    "name": "Shield",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "shield",
      "protection",
      "police gift",
      "military gift",
      "security",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/shield.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z\"/></svg>"
  },
  {
    "id": "feather-shopping-bag-v1",
    "name": "Shopping bag",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "shopping",
      "retail",
      "boutique",
      "small business",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/shopping-bag.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\"/><line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"/><path d=\"M16 10a4 4 0 0 1-8 0\"/></svg>"
  },
  {
    "id": "feather-smile-v1",
    "name": "Smiling face",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "smile",
      "happy",
      "expression",
      "kids",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/smile.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg viewBox=\"0 0 24 24\" width=\"200\" height=\"200\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M8 14s1.5 2 4 2 4-2 4-2\"/><line x1=\"9\" y1=\"9\" x2=\"9.01\" y2=\"9\"/><line x1=\"15\" y1=\"9\" x2=\"15.01\" y2=\"9\"/></svg>"
  },
  {
    "id": "feather-speaker-v1",
    "name": "Speaker",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "speaker",
      "audio",
      "music",
      "dj gift",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/speaker.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"4\" y=\"2\" width=\"16\" height=\"20\" rx=\"2\" ry=\"2\"/><circle cx=\"12\" cy=\"14\" r=\"4\"/><line x1=\"12\" y1=\"6\" x2=\"12.01\" y2=\"6\"/></svg>"
  },
  {
    "id": "feather-star-v1",
    "name": "Star outline",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "star",
      "celestial",
      "favorite",
      "award",
      "night sky",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/star.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2\"/></svg>"
  },
  {
    "id": "feather-tag-v1",
    "name": "Price tag",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "tag",
      "sale",
      "label",
      "shop",
      "retail",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/tag.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z\"/><line x1=\"7\" y1=\"7\" x2=\"7.01\" y2=\"7\"/></svg>"
  },
  {
    "id": "feather-target-v1",
    "name": "Target",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "target",
      "goal",
      "archery gift",
      "focus",
      "sales",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/target.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><circle cx=\"12\" cy=\"12\" r=\"6\"/><circle cx=\"12\" cy=\"12\" r=\"2\"/></svg>"
  },
  {
    "id": "feather-thermometer-v1",
    "name": "Thermometer",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "thermometer",
      "temperature",
      "weather",
      "health",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/thermometer.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z\"/></svg>"
  },
  {
    "id": "feather-thumbs-up-v1",
    "name": "Thumbs up",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "thumbs up",
      "approve",
      "like",
      "encouragement",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/thumbs-up.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3\"/></svg>"
  },
  {
    "id": "feather-tool-v1",
    "name": "Wrench",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "wrench",
      "tool",
      "mechanic gift",
      "handyman gift",
      "repair",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/tool.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z\"/></svg>"
  },
  {
    "id": "feather-triangle-v1",
    "name": "Triangle frame",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "triangle",
      "geometric",
      "badge",
      "frame",
      "mountain",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/triangle.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"/></svg>"
  },
  {
    "id": "feather-truck-v1",
    "name": "Delivery truck",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "truck",
      "delivery",
      "moving",
      "trucker gift",
      "logistics",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/truck.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"1\" y=\"3\" width=\"15\" height=\"13\"/><polygon points=\"16 8 20 8 23 11 23 16 16 16 16 8\"/><circle cx=\"5.5\" cy=\"18.5\" r=\"2.5\"/><circle cx=\"18.5\" cy=\"18.5\" r=\"2.5\"/></svg>"
  },
  {
    "id": "feather-umbrella-v1",
    "name": "Umbrella",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "umbrella",
      "rain",
      "weather",
      "beach",
      "shade",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/umbrella.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M23 12a11.05 11.05 0 0 0-22 0zm-5 7a3 3 0 0 1-6 0v-7\"/></svg>"
  },
  {
    "id": "feather-watch-v1",
    "name": "Wristwatch",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "watch",
      "time",
      "graduation gift",
      "retirement gift",
      "anniversary",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/watch.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"7\"/><polyline points=\"12 9 12 12 13.5 13.5\"/><path d=\"M16.51 17.35l-.35 3.83a2 2 0 0 1-2 1.82H9.83a2 2 0 0 1-2-1.82l-.35-3.83m.01-10.7l.35-3.83A2 2 0 0 1 9.83 1h4.35a2 2 0 0 1 2 1.82l.35 3.83\"/></svg>"
  },
  {
    "id": "feather-zap-v1",
    "name": "Lightning bolt",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "lightning",
      "energy",
      "power",
      "electrician gift",
      "speed",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/zap.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"13 2 3 14 12 14 11 22 21 10 12 10 13 2\"/></svg>"
  },
  {
    "id": "feather-circle-v1",
    "name": "Circle frame",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "circle",
      "geometric",
      "badge",
      "frame",
      "monogram",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/circle.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg>"
  },
  {
    "id": "feather-square-v1",
    "name": "Square frame",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "square",
      "geometric",
      "badge",
      "frame",
      "coaster",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/square.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"/></svg>"
  },
  {
    "id": "feather-video-v1",
    "name": "Video camera",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "video",
      "camera",
      "videographer gift",
      "filmmaker",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/video.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"23 7 16 12 23 17 23 7\"/><rect x=\"1\" y=\"5\" width=\"15\" height=\"14\" rx=\"2\" ry=\"2\"/></svg>"
  },
  {
    "id": "feather-users-v1",
    "name": "People group",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "people",
      "group",
      "family",
      "team",
      "community",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/users.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"/><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"/></svg>"
  },
  {
    "id": "feather-user-v1",
    "name": "Person outline",
    "kind": "element",
    "category": "Symbols & Line Art",
    "tags": [
      "person",
      "profile",
      "portrait placeholder",
      "avatar",
      "engraving",
      "sublimation",
      "line art",
      "POD design"
    ],
    "license": "MIT License — copyright and permission notice included in the SweetOh repository",
    "source": "Feather Icons — Cole Bemis and contributors",
    "sourceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/icons/user.svg",
    "evidenceUrl": "https://github.com/feathericons/feather/blob/3dc050d97405062eba78aa57115c0a15c63abdaa/LICENSE",
    "licenseId": "MIT",
    "licenseUrl": "https://opensource.org/license/mit/",
    "attributionRequired": true,
    "attributionText": "Feather Icons, Copyright (c) 2013-2023 Cole Bemis. MIT License. The copyright and permission notice must accompany copies or substantial portions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"200\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"/><circle cx=\"12\" cy=\"7\" r=\"4\"/></svg>"
  }
];
