/**
 * Studio font catalog: open-licensed Google Fonts families served on demand from the
 * Fontsource CDN (jsDelivr). Nothing here is bundled into the page; a family is fetched
 * only when it is previewed or used. Layouts store the stable key `g-<id>`.
 * Data curated from https://api.fontsource.org (OFL-1.1 / Apache-2.0 only, latin, regular weight).
 */
export const FONT_CATEGORIES = ["Sans", "Serif", "Display", "Handwriting", "Mono"] as const;
export type FontCategory = (typeof FONT_CATEGORIES)[number];
export const FONT_MOODS = ["Bold & impact", "Elegant serif", "Handwritten", "Modern sans", "Playful & rounded", "Retro & groovy", "Script & signature", "Stencil & rugged", "Tropical & display", "Typewriter & mono"] as const;
export type FontMood = (typeof FONT_MOODS)[number];

export type CatalogFont = { key: string; id: string; family: string; category: FontCategory; mood: FontMood; bold: boolean; license: "OFL-1.1" | "Apache-2.0" };

const ROWS: readonly [string, string, FontCategory, FontMood, 0 | 1, "OFL-1.1" | "Apache-2.0"][] = [["bowlby-one", "Bowlby One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["bowlby-one-sc", "Bowlby One SC", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["passion-one", "Passion One", "Display", "Bold & impact", 1, "OFL-1.1"],
  ["luckiest-guy", "Luckiest Guy", "Display", "Bold & impact", 0, "Apache-2.0"],
  ["black-ops-one", "Black Ops One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["russo-one", "Russo One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["rammetto-one", "Rammetto One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["chango", "Chango", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["titan-one", "Titan One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["paytone-one", "Paytone One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["sigmar-one", "Sigmar One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["bungee", "Bungee", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["bungee-inline", "Bungee Inline", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["bungee-shade", "Bungee Shade", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["squada-one", "Squada One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["fugaz-one", "Fugaz One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["days-one", "Days One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["gasoek-one", "Gasoek One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["rubik-mono-one", "Rubik Mono One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["climate-crisis", "Climate Crisis", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["dela-gothic-one", "Dela Gothic One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["big-shoulders-display", "Big Shoulders Display", "Display", "Bold & impact", 1, "OFL-1.1"],
  ["big-shoulders-stencil-display", "Big Shoulders Stencil Display", "Display", "Bold & impact", 1, "OFL-1.1"],
  ["league-gothic", "League Gothic", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["fjalla-one", "Fjalla One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["pathway-gothic-one", "Pathway Gothic One", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["teko", "Teko", "Sans", "Bold & impact", 1, "OFL-1.1"],
  ["saira-extra-condensed", "Saira Extra Condensed", "Sans", "Bold & impact", 1, "OFL-1.1"],
  ["antonio", "Antonio", "Sans", "Bold & impact", 1, "OFL-1.1"],
  ["six-caps", "Six Caps", "Sans", "Bold & impact", 0, "OFL-1.1"],
  ["stint-ultra-condensed", "Stint Ultra Condensed", "Serif", "Bold & impact", 0, "OFL-1.1"],
  ["holtwood-one-sc", "Holtwood One SC", "Serif", "Bold & impact", 0, "OFL-1.1"],
  ["ultra", "Ultra", "Serif", "Bold & impact", 0, "Apache-2.0"],
  ["shrikhand", "Shrikhand", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["rozha-one", "Rozha One", "Serif", "Bold & impact", 0, "OFL-1.1"],
  ["gravitas-one", "Gravitas One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["racing-sans-one", "Racing Sans One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["carter-one", "Carter One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["changa-one", "Changa One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["concert-one", "Concert One", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["chelsea-market", "Chelsea Market", "Display", "Bold & impact", 0, "OFL-1.1"],
  ["sansita-swashed", "Sansita Swashed", "Display", "Bold & impact", 1, "OFL-1.1"],
  ["kaushan-script", "Kaushan Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["courgette", "Courgette", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["yellowtail", "Yellowtail", "Handwriting", "Script & signature", 0, "Apache-2.0"],
  ["parisienne", "Parisienne", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["allura", "Allura", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["alex-brush", "Alex Brush", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["lobster-two", "Lobster Two", "Display", "Script & signature", 1, "OFL-1.1"],
  ["cookie", "Cookie", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["damion", "Damion", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["norican", "Norican", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["marck-script", "Marck Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["pinyon-script", "Pinyon Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["tangerine", "Tangerine", "Handwriting", "Script & signature", 1, "OFL-1.1"],
  ["mr-dafoe", "Mr Dafoe", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["arizonia", "Arizonia", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["satisfy", "Satisfy", "Handwriting", "Script & signature", 0, "Apache-2.0"],
  ["playball", "Playball", "Display", "Script & signature", 0, "OFL-1.1"],
  ["rochester", "Rochester", "Handwriting", "Script & signature", 0, "Apache-2.0"],
  ["berkshire-swash", "Berkshire Swash", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["niconne", "Niconne", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["bilbo-swash-caps", "Bilbo Swash Caps", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["euphoria-script", "Euphoria Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["herr-von-muellerhoff", "Herr Von Muellerhoff", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["mrs-saint-delafield", "Mrs Saint Delafield", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["monsieur-la-doulaise", "Monsieur La Doulaise", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["meddon", "Meddon", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["qwigley", "Qwigley", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["ruthie", "Ruthie", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["petit-formal-script", "Petit Formal Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["ballet", "Ballet", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["corinthia", "Corinthia", "Handwriting", "Script & signature", 1, "OFL-1.1"],
  ["italianno", "Italianno", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["kristi", "Kristi", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["lovers-quarrel", "Lovers Quarrel", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["miss-fajardose", "Miss Fajardose", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["over-the-rainbow", "Over the Rainbow", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["sofia", "Sofia", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["stalemate", "Stalemate", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["waterfall", "Waterfall", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["zeyada", "Zeyada", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["vibur", "Vibur", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["oleo-script", "Oleo Script", "Display", "Script & signature", 1, "OFL-1.1"],
  ["oleo-script-swash-caps", "Oleo Script Swash Caps", "Display", "Script & signature", 1, "OFL-1.1"],
  ["merienda", "Merienda", "Handwriting", "Script & signature", 1, "OFL-1.1"],
  ["grand-hotel", "Grand Hotel", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["leckerli-one", "Leckerli One", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["sail", "Sail", "Display", "Script & signature", 0, "OFL-1.1"],
  ["style-script", "Style Script", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["mynerve", "Mynerve", "Handwriting", "Script & signature", 0, "OFL-1.1"],
  ["indie-flower", "Indie Flower", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["gloria-hallelujah", "Gloria Hallelujah", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["patrick-hand", "Patrick Hand", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["covered-by-your-grace", "Covered By Your Grace", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["reenie-beanie", "Reenie Beanie", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["rock-salt", "Rock Salt", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["nanum-pen-script", "Nanum Pen Script", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["architects-daughter", "Architects Daughter", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["amatic-sc", "Amatic SC", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["gaegu", "Gaegu", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["handlee", "Handlee", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["just-another-hand", "Just Another Hand", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["schoolbell", "Schoolbell", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["short-stack", "Short Stack", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["swanky-and-moo-moo", "Swanky and Moo Moo", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["walter-turncoat", "Walter Turncoat", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["yomogi", "Yomogi", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["coming-soon", "Coming Soon", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["crafty-girls", "Crafty Girls", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["dekko", "Dekko", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["delicious-handrawn", "Delicious Handrawn", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["gochi-hand", "Gochi Hand", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["neucha", "Neucha", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["nothing-you-could-do", "Nothing You Could Do", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["patrick-hand-sc", "Patrick Hand SC", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["rancho", "Rancho", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["sue-ellen-francisco", "Sue Ellen Francisco", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["waiting-for-the-sunrise", "Waiting for the Sunrise", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["annie-use-your-telescope", "Annie Use Your Telescope", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["cedarville-cursive", "Cedarville Cursive", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["homemade-apple", "Homemade Apple", "Handwriting", "Handwritten", 0, "Apache-2.0"],
  ["loved-by-the-king", "Loved by the King", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["mansalva", "Mansalva", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["nanum-brush-script", "Nanum Brush Script", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["oooh-baby", "Oooh Baby", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["sedgwick-ave", "Sedgwick Ave", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["sedgwick-ave-display", "Sedgwick Ave Display", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["shantell-sans", "Shantell Sans", "Display", "Handwritten", 1, "OFL-1.1"],
  ["single-day", "Single Day", "Display", "Handwritten", 0, "OFL-1.1"],
  ["the-girl-next-door", "The Girl Next Door", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["vujahday-script", "Vujahday Script", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["caveat-brush", "Caveat Brush", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["la-belle-aurore", "La Belle Aurore", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["pangolin", "Pangolin", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["sriracha", "Sriracha", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["itim", "Itim", "Handwriting", "Handwritten", 0, "OFL-1.1"],
  ["mali", "Mali", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["fuzzy-bubbles", "Fuzzy Bubbles", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["playpen-sans", "Playpen Sans", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["comic-neue", "Comic Neue", "Handwriting", "Handwritten", 1, "OFL-1.1"],
  ["cormorant-garamond", "Cormorant Garamond", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cormorant", "Cormorant", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cormorant-infant", "Cormorant Infant", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cormorant-upright", "Cormorant Upright", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cormorant-unicase", "Cormorant Unicase", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cormorant-sc", "Cormorant SC", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["cinzel-decorative", "Cinzel Decorative", "Display", "Elegant serif", 1, "OFL-1.1"],
  ["libre-baskerville", "Libre Baskerville", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["lora", "Lora", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["merriweather", "Merriweather", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["dm-serif-text", "DM Serif Text", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["bodoni-moda", "Bodoni Moda", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["prata", "Prata", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["gilda-display", "Gilda Display", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["marcellus", "Marcellus", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["marcellus-sc", "Marcellus SC", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["cardo", "Cardo", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["crimson-text", "Crimson Text", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["crimson-pro", "Crimson Pro", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["eb-garamond", "EB Garamond", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["spectral", "Spectral", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["vollkorn", "Vollkorn", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["old-standard-tt", "Old Standard TT", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["playfair-display-sc", "Playfair Display SC", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["fanwood-text", "Fanwood Text", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["italiana", "Italiana", "Sans", "Elegant serif", 0, "OFL-1.1"],
  ["forum", "Forum", "Display", "Elegant serif", 0, "OFL-1.1"],
  ["gloock", "Gloock", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["young-serif", "Young Serif", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["bellefair", "Bellefair", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["rufina", "Rufina", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["yeseva-one", "Yeseva One", "Display", "Elegant serif", 0, "OFL-1.1"],
  ["trirong", "Trirong", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["noto-serif-display", "Noto Serif Display", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["libre-caslon-display", "Libre Caslon Display", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["libre-caslon-text", "Libre Caslon Text", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["libre-bodoni", "Libre Bodoni", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["baskervville", "Baskervville", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["sorts-mill-goudy", "Sorts Mill Goudy", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["ibarra-real-nova", "Ibarra Real Nova", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["castoro", "Castoro", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["belleza", "Belleza", "Sans", "Elegant serif", 0, "OFL-1.1"],
  ["stoke", "Stoke", "Serif", "Elegant serif", 0, "OFL-1.1"],
  ["tinos", "Tinos", "Serif", "Elegant serif", 1, "OFL-1.1"],
  ["manrope", "Manrope", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["plus-jakarta-sans", "Plus Jakarta Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["outfit", "Outfit", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["sora", "Sora", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["lexend", "Lexend", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["urbanist", "Urbanist", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["figtree", "Figtree", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["jost", "Jost", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["mulish", "Mulish", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["quicksand", "Quicksand", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["karla", "Karla", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["barlow", "Barlow", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["cabin", "Cabin", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["hind", "Hind", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["heebo", "Heebo", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["mukta", "Mukta", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["prompt", "Prompt", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["kanit", "Kanit", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["sarabun", "Sarabun", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["red-hat-display", "Red Hat Display", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["red-hat-text", "Red Hat Text", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["be-vietnam-pro", "Be Vietnam Pro", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["albert-sans", "Albert Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["epilogue", "Epilogue", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["syne", "Syne", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["unbounded", "Unbounded", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["space-mono", "Space Mono", "Mono", "Modern sans", 1, "OFL-1.1"],
  ["archivo", "Archivo", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["josefin-sans", "Josefin Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["josefin-slab", "Josefin Slab", "Serif", "Modern sans", 1, "OFL-1.1"],
  ["nunito-sans", "Nunito Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["source-sans-3", "Source Sans 3", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["ibm-plex-sans", "IBM Plex Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["noto-sans", "Noto Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["roboto", "Roboto", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["roboto-condensed", "Roboto Condensed", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["pt-sans", "PT Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["titillium-web", "Titillium Web", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["exo-2", "Exo 2", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["oxygen", "Oxygen", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["asap", "Asap", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["assistant", "Assistant", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["overpass", "Overpass", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["questrial", "Questrial", "Sans", "Modern sans", 0, "OFL-1.1"],
  ["varela-round", "Varela Round", "Sans", "Modern sans", 0, "OFL-1.1"],
  ["comfortaa", "Comfortaa", "Display", "Modern sans", 1, "OFL-1.1"],
  ["baloo-2", "Baloo 2", "Display", "Modern sans", 1, "OFL-1.1"],
  ["m-plus-rounded-1c", "M PLUS Rounded 1c", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["nanum-gothic", "Nanum Gothic", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["abeezee", "ABeeZee", "Sans", "Modern sans", 0, "OFL-1.1"],
  ["public-sans", "Public Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["onest", "Onest", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["geologica", "Geologica", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["instrument-sans", "Instrument Sans", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["schibsted-grotesk", "Schibsted Grotesk", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["bricolage-grotesque", "Bricolage Grotesque", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["hanken-grotesk", "Hanken Grotesk", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["readex-pro", "Readex Pro", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["commissioner", "Commissioner", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["golos-text", "Golos Text", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["anek-latin", "Anek Latin", "Sans", "Modern sans", 1, "OFL-1.1"],
  ["monoton", "Monoton", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["fredericka-the-great", "Fredericka the Great", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["limelight", "Limelight", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["sonsie-one", "Sonsie One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rampart-one", "Rampart One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-glitch", "Rubik Glitch", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-marker-hatch", "Rubik Marker Hatch", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-bubbles", "Rubik Bubbles", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-wet-paint", "Rubik Wet Paint", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-spray-paint", "Rubik Spray Paint", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-iso", "Rubik Iso", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-burned", "Rubik Burned", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-vinyl", "Rubik Vinyl", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-maze", "Rubik Maze", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-dirt", "Rubik Dirt", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-distressed", "Rubik Distressed", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-doodle-shadow", "Rubik Doodle Shadow", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-puddles", "Rubik Puddles", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-scribble", "Rubik Scribble", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-beastly", "Rubik Beastly", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-moonrocks", "Rubik Moonrocks", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-pixels", "Rubik Pixels", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-storm", "Rubik Storm", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-microbe", "Rubik Microbe", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-gemstones", "Rubik Gemstones", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-lines", "Rubik Lines", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-maps", "Rubik Maps", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rubik-broken-fax", "Rubik Broken Fax", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["bungee-hairline", "Bungee Hairline", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["modak", "Modak", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["coiny", "Coiny", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["lemon", "Lemon", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["londrina-solid", "Londrina Solid", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["londrina-shadow", "Londrina Shadow", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["londrina-outline", "Londrina Outline", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["londrina-sketch", "Londrina Sketch", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["ranchers", "Ranchers", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["sniglet", "Sniglet", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["spicy-rice", "Spicy Rice", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["gorditas", "Gorditas", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["oi", "Oi", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["emilys-candy", "Emilys Candy", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["butcherman", "Butcherman", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["creepster", "Creepster", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["eater", "Eater", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["nosifer", "Nosifer", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["metal-mania", "Metal Mania", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["faster-one", "Faster One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["black-han-sans", "Black Han Sans", "Sans", "Retro & groovy", 0, "OFL-1.1"],
  ["bigelow-rules", "Bigelow Rules", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["monofett", "Monofett", "Mono", "Retro & groovy", 0, "OFL-1.1"],
  ["vast-shadow", "Vast Shadow", "Serif", "Retro & groovy", 0, "OFL-1.1"],
  ["bungee-outline", "Bungee Outline", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["fascinate", "Fascinate", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["fascinate-inline", "Fascinate Inline", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["vampiro-one", "Vampiro One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["ewert", "Ewert", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["diplomata", "Diplomata", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["diplomata-sc", "Diplomata SC", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["kumar-one", "Kumar One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["kumar-one-outline", "Kumar One Outline", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["sancreek", "Sancreek", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["rye", "Rye", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["smokum", "Smokum", "Display", "Retro & groovy", 0, "Apache-2.0"],
  ["ribeye", "Ribeye", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["ribeye-marrow", "Ribeye Marrow", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["new-rocker", "New Rocker", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["eagle-lake", "Eagle Lake", "Handwriting", "Retro & groovy", 0, "OFL-1.1"],
  ["mystery-quest", "Mystery Quest", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["almendra", "Almendra", "Serif", "Retro & groovy", 1, "OFL-1.1"],
  ["almendra-display", "Almendra Display", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["uncial-antiqua", "Uncial Antiqua", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["macondo", "Macondo", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["macondo-swash-caps", "Macondo Swash Caps", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["jolly-lodger", "Jolly Lodger", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["henny-penny", "Henny Penny", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["griffy", "Griffy", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["gafata", "Gafata", "Sans", "Retro & groovy", 0, "OFL-1.1"],
  ["bubblegum-sans", "Bubblegum Sans", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["knewave", "Knewave", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["caesar-dressing", "Caesar Dressing", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["audiowide", "Audiowide", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["orbitron", "Orbitron", "Sans", "Retro & groovy", 1, "OFL-1.1"],
  ["press-start-2p", "Press Start 2P", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["vt323", "VT323", "Mono", "Retro & groovy", 0, "OFL-1.1"],
  ["silkscreen", "Silkscreen", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["jersey-10", "Jersey 10", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["pixelify-sans", "Pixelify Sans", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["tourney", "Tourney", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["iceland", "Iceland", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["major-mono-display", "Major Mono Display", "Mono", "Retro & groovy", 0, "OFL-1.1"],
  ["share-tech-mono", "Share Tech Mono", "Mono", "Retro & groovy", 0, "OFL-1.1"],
  ["nova-mono", "Nova Mono", "Mono", "Retro & groovy", 0, "OFL-1.1"],
  ["zen-dots", "Zen Dots", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["oxanium", "Oxanium", "Display", "Retro & groovy", 1, "OFL-1.1"],
  ["michroma", "Michroma", "Sans", "Retro & groovy", 0, "OFL-1.1"],
  ["syncopate", "Syncopate", "Sans", "Retro & groovy", 1, "Apache-2.0"],
  ["wallpoet", "Wallpoet", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["stalinist-one", "Stalinist One", "Display", "Retro & groovy", 0, "OFL-1.1"],
  ["baloo-bhai-2", "Baloo Bhai 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["baloo-da-2", "Baloo Da 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["baloo-paaji-2", "Baloo Paaji 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["baloo-tamma-2", "Baloo Tamma 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["baloo-tammudu-2", "Baloo Tammudu 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["baloo-thambi-2", "Baloo Thambi 2", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["chewy", "Chewy", "Display", "Playful & rounded", 0, "Apache-2.0"],
  ["gluten", "Gluten", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["grandstander", "Grandstander", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["mochiy-pop-one", "Mochiy Pop One", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["mochiy-pop-p-one", "Mochiy Pop P One", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["potta-one", "Potta One", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["skranji", "Skranji", "Display", "Playful & rounded", 1, "OFL-1.1"],
  ["happy-monkey", "Happy Monkey", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["cherry-bomb-one", "Cherry Bomb One", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["yusei-magic", "Yusei Magic", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["kiwi-maru", "Kiwi Maru", "Serif", "Playful & rounded", 0, "OFL-1.1"],
  ["klee-one", "Klee One", "Handwriting", "Playful & rounded", 1, "OFL-1.1"],
  ["zen-maru-gothic", "Zen Maru Gothic", "Sans", "Playful & rounded", 1, "OFL-1.1"],
  ["zen-kurenaido", "Zen Kurenaido", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["kablammo", "Kablammo", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["bagel-fat-one", "Bagel Fat One", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["borel", "Borel", "Handwriting", "Playful & rounded", 0, "OFL-1.1"],
  ["mouse-memoirs", "Mouse Memoirs", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["dongle", "Dongle", "Sans", "Playful & rounded", 1, "OFL-1.1"],
  ["gamja-flower", "Gamja Flower", "Handwriting", "Playful & rounded", 0, "OFL-1.1"],
  ["poor-story", "Poor Story", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["hi-melody", "Hi Melody", "Handwriting", "Playful & rounded", 0, "OFL-1.1"],
  ["do-hyeon", "Do Hyeon", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["jua", "Jua", "Sans", "Playful & rounded", 0, "OFL-1.1"],
  ["yeon-sung", "Yeon Sung", "Display", "Playful & rounded", 0, "OFL-1.1"],
  ["special-elite", "Special Elite", "Display", "Typewriter & mono", 0, "Apache-2.0"],
  ["courier-prime", "Courier Prime", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["cutive-mono", "Cutive Mono", "Mono", "Typewriter & mono", 0, "OFL-1.1"],
  ["ibm-plex-mono", "IBM Plex Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["jetbrains-mono", "JetBrains Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["fira-code", "Fira Code", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["fira-mono", "Fira Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["source-code-pro", "Source Code Pro", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["roboto-mono", "Roboto Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["dm-mono", "DM Mono", "Mono", "Typewriter & mono", 0, "OFL-1.1"],
  ["red-hat-mono", "Red Hat Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["inconsolata", "Inconsolata", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["anonymous-pro", "Anonymous Pro", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["overpass-mono", "Overpass Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["sometype-mono", "Sometype Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["martian-mono", "Martian Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["azeret-mono", "Azeret Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["xanh-mono", "Xanh Mono", "Mono", "Typewriter & mono", 0, "OFL-1.1"],
  ["b612-mono", "B612 Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["syne-mono", "Syne Mono", "Mono", "Typewriter & mono", 0, "OFL-1.1"],
  ["kode-mono", "Kode Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["geist-mono", "Geist Mono", "Mono", "Typewriter & mono", 1, "OFL-1.1"],
  ["stardos-stencil", "Stardos Stencil", "Display", "Stencil & rugged", 1, "OFL-1.1"],
  ["saira-stencil-one", "Saira Stencil One", "Display", "Stencil & rugged", 0, "OFL-1.1"],
  ["allerta-stencil", "Allerta Stencil", "Sans", "Stencil & rugged", 0, "OFL-1.1"],
  ["sirin-stencil", "Sirin Stencil", "Display", "Stencil & rugged", 0, "OFL-1.1"],
  ["emblema-one", "Emblema One", "Display", "Stencil & rugged", 0, "OFL-1.1"],
  ["graduate", "Graduate", "Serif", "Stencil & rugged", 0, "OFL-1.1"],
  ["league-spartan", "League Spartan", "Sans", "Stencil & rugged", 1, "OFL-1.1"],
  ["chivo-mono", "Chivo Mono", "Mono", "Stencil & rugged", 1, "OFL-1.1"],
  ["slackey", "Slackey", "Display", "Stencil & rugged", 0, "Apache-2.0"],
  ["bevan", "Bevan", "Serif", "Stencil & rugged", 0, "OFL-1.1"],
  ["arvo", "Arvo", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["roboto-slab", "Roboto Slab", "Serif", "Stencil & rugged", 1, "Apache-2.0"],
  ["zilla-slab", "Zilla Slab", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["rokkitt", "Rokkitt", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["bitter", "Bitter", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["crete-round", "Crete Round", "Serif", "Stencil & rugged", 0, "OFL-1.1"],
  ["patua-one", "Patua One", "Display", "Stencil & rugged", 0, "OFL-1.1"],
  ["aleo", "Aleo", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["chonburi", "Chonburi", "Display", "Stencil & rugged", 0, "OFL-1.1"],
  ["gelasio", "Gelasio", "Serif", "Stencil & rugged", 1, "OFL-1.1"],
  ["sigmar", "Sigmar", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["coustard", "Coustard", "Serif", "Tropical & display", 1, "OFL-1.1"],
  ["bree-serif", "Bree Serif", "Serif", "Tropical & display", 0, "OFL-1.1"],
  ["ruslan-display", "Ruslan Display", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["marko-one", "Marko One", "Serif", "Tropical & display", 0, "OFL-1.1"],
  ["sansita", "Sansita", "Sans", "Tropical & display", 1, "OFL-1.1"],
  ["fontdiner-swanky", "Fontdiner Swanky", "Display", "Tropical & display", 0, "Apache-2.0"],
  ["galada", "Galada", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["hanalei", "Hanalei", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["hanalei-fill", "Hanalei Fill", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["kavoon", "Kavoon", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["lily-script-one", "Lily Script One", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["love-ya-like-a-sister", "Love Ya Like A Sister", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["merienda-one", "Merienda One", "Handwriting", "Tropical & display", 0, "OFL-1.1"],
  ["mogra", "Mogra", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["pirata-one", "Pirata One", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["piedra", "Piedra", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["rum-raisin", "Rum Raisin", "Sans", "Tropical & display", 0, "OFL-1.1"],
  ["sarina", "Sarina", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["trade-winds", "Trade Winds", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["yuji-boku", "Yuji Boku", "Serif", "Tropical & display", 0, "OFL-1.1"],
  ["yuji-syuku", "Yuji Syuku", "Serif", "Tropical & display", 0, "OFL-1.1"],
  ["chicle", "Chicle", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["ceviche-one", "Ceviche One", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["geostar", "Geostar", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["geostar-fill", "Geostar Fill", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["fruktur", "Fruktur", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["original-surfer", "Original Surfer", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["ruge-boogie", "Ruge Boogie", "Handwriting", "Tropical & display", 0, "OFL-1.1"],
  ["snippet", "Snippet", "Sans", "Tropical & display", 0, "OFL-1.1"],
  ["text-me-one", "Text Me One", "Sans", "Tropical & display", 0, "OFL-1.1"],
  ["wendy-one", "Wendy One", "Sans", "Tropical & display", 0, "OFL-1.1"],
  ["lemonada", "Lemonada", "Display", "Tropical & display", 1, "OFL-1.1"],
  ["jomhuria", "Jomhuria", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["atma", "Atma", "Display", "Tropical & display", 1, "OFL-1.1"],
  ["baumans", "Baumans", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["bonbon", "Bonbon", "Handwriting", "Tropical & display", 0, "OFL-1.1"],
  ["fondamento", "Fondamento", "Handwriting", "Tropical & display", 0, "OFL-1.1"],
  ["kenia", "Kenia", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["modern-antiqua", "Modern Antiqua", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["nixie-one", "Nixie One", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["overlock", "Overlock", "Display", "Tropical & display", 1, "OFL-1.1"],
  ["redressed", "Redressed", "Handwriting", "Tropical & display", 0, "Apache-2.0"],
  ["risque", "Risque", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["rock-3d", "Rock 3D", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["romanesco", "Romanesco", "Handwriting", "Tropical & display", 0, "OFL-1.1"],
  ["shojumaru", "Shojumaru", "Display", "Tropical & display", 0, "OFL-1.1"],
  ["stint-ultra-expanded", "Stint Ultra Expanded", "Serif", "Tropical & display", 0, "OFL-1.1"],
  ["unkempt", "Unkempt", "Display", "Tropical & display", 1, "Apache-2.0"],
  ["trochut", "Trochut", "Display", "Tropical & display", 1, "OFL-1.1"],
  ["yatra-one", "Yatra One", "Display", "Tropical & display", 0, "OFL-1.1"]];

export const FONT_CATALOG: readonly CatalogFont[] = ROWS.map(([id, family, category, mood, bold, license]) => ({ key: `g-${id}`, id, family, category, mood, bold: bold === 1, license }));
const BY_KEY = new Map(FONT_CATALOG.map((font) => [font.key, font]));
export function catalogFont(key: string | undefined): CatalogFont | undefined {
  return key ? BY_KEY.get(key) : undefined;
}
