/** Generated from CC0 Mesoamerican huipil textile photographs (National Museum of World Cultures, Netherlands, via Europeana). Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const HUIPIL_TEXTILES_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "huipil-huipil-1-geometric-red-v1",
    "name": "Huipil with red and magenta geometric bands",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "huipil",
      "Mexican textile",
      "Guatemalan textile",
      "Mesoamerican",
      "indigenous textile",
      "embroidery",
      "geometric pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_851655",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5946-653.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Huipil with red and magenta geometric bands. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/huipil-textiles/huipil-1-geometric-red.webp",
    "width": 2093,
    "height": 2400
  },
  {
    "id": "huipil-huipil-2-floral-embroidered-v1",
    "name": "Huipil with floral vine embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "huipil",
      "Mexican textile",
      "Guatemalan textile",
      "Mesoamerican",
      "indigenous textile",
      "embroidery",
      "floral pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_804358",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5075-410.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Huipil with floral vine embroidery. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/huipil-textiles/huipil-2-floral-embroidered.webp",
    "width": 2400,
    "height": 1821
  },
  {
    "id": "huipil-huipil-3-llama-motifs-v1",
    "name": "Huipil with llama and star motifs (natural dye)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "huipil",
      "Guatemalan textile",
      "Mesoamerican",
      "indigenous textile",
      "embroidery",
      "llama",
      "animal motif",
      "natural dye",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_851120",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5946-171.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Huipil with llama and star motifs (natural dye). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/huipil-textiles/huipil-3-llama-motifs.webp",
    "width": 2400,
    "height": 1800
  },
  {
    "id": "huipil-huipil-4-triangle-collar-v1",
    "name": "Huipil with colorful triangle-motif collar embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "huipil",
      "Guatemalan textile",
      "Mesoamerican",
      "indigenous textile",
      "embroidery",
      "triangle motif",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_851516",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5946-528.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Huipil with colorful triangle-motif collar embroidery. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/huipil-textiles/huipil-4-triangle-collar.webp",
    "width": 2400,
    "height": 1920
  },
  {
    "id": "huipil-huipil-6-floral-bouquet-v1",
    "name": "Huipil with floral bouquet embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "huipil",
      "Mexican textile",
      "Guatemalan textile",
      "Mesoamerican",
      "indigenous textile",
      "embroidery",
      "floral pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_803999",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5075-79.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Huipil with floral bouquet embroidery. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/huipil-textiles/huipil-6-floral-bouquet.webp",
    "width": 2400,
    "height": 1868
  }
];
