/** Generated from CC0 Indonesian textile photographs (National Museum of World Cultures, Netherlands, via Europeana). Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const INDONESIAN_TEXTILES_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "indonesian-textile-batik-sample-v1",
    "name": "Batik (sample)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "batik",
      "Indonesian textile",
      "Indonesia",
      "wax-resist dye",
      "textile design",
      "pattern reference",
      "global folk art",
      "sublimation",
      "craft gift",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_661149",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-499-99.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Batik (sample). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/batik-sample.webp",
    "width": 2400,
    "height": 984
  },
  {
    "id": "indonesian-textile-batik-sekar-pala-v1",
    "name": "Batik pattern: Sekar pala",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "batik",
      "sekar pala",
      "Indonesian textile",
      "Indonesia",
      "geometric pattern",
      "wax-resist dye",
      "textile design",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_674260",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-847-7.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Batik pattern: Sekar pala. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/batik-sekar-pala.webp",
    "width": 2358,
    "height": 2400
  },
  {
    "id": "indonesian-textile-ikat-cloth-v1",
    "name": "Ikat cloth",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ikat",
      "Indonesian textile",
      "Indonesia",
      "woven cloth",
      "textile design",
      "striped pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_733868",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-2074-5.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Ikat cloth. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/ikat-cloth.webp",
    "width": 2400,
    "height": 1920
  },
  {
    "id": "indonesian-textile-ikat-cloth-2-v1",
    "name": "Ikat cloth",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ikat",
      "Indonesian textile",
      "Indonesia",
      "woven cloth",
      "textile design",
      "striped pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_786603",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-4160-46.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Ikat cloth. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/ikat-cloth-2.webp",
    "width": 2400,
    "height": 948
  },
  {
    "id": "indonesian-textile-ikat-triangle-motifs-v1",
    "name": "Ikat cloth with triangle motifs",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ikat",
      "triangle motif",
      "Indonesian textile",
      "Indonesia",
      "geometric pattern",
      "textile design",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_785029",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-4032-15.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Ikat cloth with triangle motifs. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/ikat-triangle-motifs.webp",
    "width": 2400,
    "height": 1456
  },
  {
    "id": "indonesian-textile-ikat-sarong-blue-red-v1",
    "name": "Blue-red ikat sarong",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ikat",
      "sarong",
      "Indonesian textile",
      "Indonesia",
      "striped pattern",
      "textile design",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_1030206",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/NMVW/7038-2.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Blue-red ikat sarong. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/ikat-sarong-blue-red.webp",
    "width": 1524,
    "height": 2400
  },
  {
    "id": "indonesian-textile-kain-panjang-v1",
    "name": "Kain panjang (long cloth)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kain panjang",
      "Indonesian textile",
      "Indonesia",
      "Javanese textile",
      "textile design",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_1038053",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/NMVW/7082-S-4393-31.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kain panjang (long cloth). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/kain-panjang.webp",
    "width": 2400,
    "height": 2003
  },
  {
    "id": "indonesian-textile-kain-prada-gold-v1",
    "name": "Kain prada (gold-leaf cloth)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kain prada",
      "gold leaf",
      "Indonesian textile",
      "Indonesia",
      "floral pattern",
      "luxury textile",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_1035994",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/NMVW/7082-S-371-1.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kain prada (gold-leaf cloth). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/kain-prada-gold.webp",
    "width": 1749,
    "height": 2400
  },
  {
    "id": "indonesian-textile-songket-kain-v1",
    "name": "Kain songket (gold-thread cloth)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "songket",
      "gold thread",
      "Indonesian textile",
      "Indonesia",
      "woven pattern",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_1036614",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/NMVW/7082-S-451-3843.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kain songket (gold-thread cloth). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/songket-kain.webp",
    "width": 2400,
    "height": 1736
  },
  {
    "id": "indonesian-textile-ceremonial-cloth-geometric-v1",
    "name": "Silk ceremonial cloth with geometric and animal figures",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "ceremonial cloth",
      "weft ikat",
      "silk",
      "Indonesian textile",
      "Indonesia",
      "geometric pattern",
      "animal motif",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_66157",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/TM/TM-1772-1508.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Silk ceremonial cloth with geometric and animal figures. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/indonesian-textiles/ceremonial-cloth-geometric.webp",
    "width": 1500,
    "height": 1125
  }
];
