/** Generated from CC0 Ghanaian kente cloth photographs (National Museum of World Cultures, Netherlands, via Europeana). Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const KENTE_CLOTH_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "kente-kente-1-v1",
    "name": "Kente cloth for a woman",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kente",
      "Ghanaian textile",
      "Akan",
      "Ghana",
      "West African textile",
      "woven pattern",
      "geometric",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_842919",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5899-67.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kente cloth for a woman. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/kente-cloth/kente-1.webp",
    "width": 2400,
    "height": 1338
  },
  {
    "id": "kente-kente-2-v1",
    "name": "Kente cloth for a man",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kente",
      "Ghanaian textile",
      "Akan",
      "Ghana",
      "West African textile",
      "woven pattern",
      "geometric",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_842896",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5899-44.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kente cloth for a man. Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/kente-cloth/kente-2.webp",
    "width": 2400,
    "height": 1597
  },
  {
    "id": "kente-kente-3-v1",
    "name": "Kente cloth for a man (green ground with figurative motifs)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kente",
      "Ghanaian textile",
      "Akan",
      "Ghana",
      "West African textile",
      "woven pattern",
      "figurative motif",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_842862",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5899-10.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kente cloth for a man (green ground with figurative motifs). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/kente-cloth/kente-3.webp",
    "width": 2400,
    "height": 1221
  },
  {
    "id": "kente-kente-4-v1",
    "name": "Kente cloth (houndstooth ground with woven stripes)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kente",
      "Ghanaian textile",
      "Akan",
      "Ghana",
      "West African textile",
      "woven pattern",
      "geometric",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_842866",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5899-14.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kente cloth (houndstooth ground with woven stripes). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/kente-cloth/kente-4.webp",
    "width": 2400,
    "height": 1450
  },
  {
    "id": "kente-kente-5-v1",
    "name": "Kente cloth (navy ground with gold and red bands)",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "kente",
      "Ghanaian textile",
      "Akan",
      "Ghana",
      "West African textile",
      "woven pattern",
      "geometric",
      "global folk art",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "CC0 1.0 Universal — public domain dedication",
    "source": "National Museum of World Cultures (Netherlands), via Europeana",
    "sourceUrl": "https://www.europeana.eu/item/2048221/europeana_fashion_842872",
    "evidenceUrl": "http://collectie.wereldculturen.nl/cc/imageproxy.ashx?server=localhost&port=17581&filename=images//Images/RV/RV-5899-20.jpg",
    "licenseId": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "attributionRequired": false,
    "attributionText": "Kente cloth (navy ground with gold and red bands). Credit: National Museum of World Cultures (Netherlands), via Europeana. CC0 1.0 Universal.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/kente-cloth/kente-5.webp",
    "width": 2400,
    "height": 979
  }
];
