/** Generated from Public Domain Mark Wellcome Collection entomological engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_INSECTS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-insects-dragonflies-mayflies-v1",
    "name": "Five dragonflies and four mayflies",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "dragonfly",
      "mayfly",
      "insect",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "garden gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Newton after James Barbut",
    "sourceUrl": "https://wellcomecollection.org/works/k9xecxkk",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022511ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Five dragonflies and four mayflies. Engraving by J. Newton after James Barbut. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/dragonflies-mayflies.webp",
    "width": 1751,
    "height": 2400
  },
  {
    "id": "wellcome-insects-lepidoptera-seven-insects-v1",
    "name": "Seven insects of the order Lepidoptera, including butterflies and moths",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "butterfly",
      "moth",
      "lepidoptera",
      "insect",
      "entomology",
      "engraving",
      "line art",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Thomas Milton",
    "sourceUrl": "https://wellcomecollection.org/works/j9wjm5u9",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020562ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Seven insects of the order Lepidoptera, including butterflies and moths. Engraving by Thomas Milton. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/lepidoptera-seven-insects.webp",
    "width": 1966,
    "height": 2400
  },
  {
    "id": "wellcome-insects-insect-variety-beetles-wasps-v1",
    "name": "A variety of insect life including beetles, wasps and dragonflies",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "beetle",
      "wasp",
      "dragonfly",
      "insect",
      "entomology",
      "engraving",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — R. Scott after Thomas Brown",
    "sourceUrl": "https://wellcomecollection.org/works/ut654r7y",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022738ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A variety of insect life including beetles, wasps and dragonflies. Engraving by R. Scott after Thomas Brown. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/insect-variety-beetles-wasps.webp",
    "width": 1455,
    "height": 2400
  },
  {
    "id": "wellcome-insects-scarabaeus-beetle-v1",
    "name": "A male scarabaeus beetle",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "beetle",
      "scarab",
      "insect",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Home Lizars",
    "sourceUrl": "https://wellcomecollection.org/works/krf7bcgs",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020757/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A male scarabaeus beetle. Engraving by William Home Lizars. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/scarabaeus-beetle.webp",
    "width": 2000,
    "height": 1108
  },
  {
    "id": "wellcome-insects-six-beetles-stag-beetle-v1",
    "name": "Six beetles including a stag beetle",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "beetle",
      "stag beetle",
      "insect",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — I. O. W.",
    "sourceUrl": "https://wellcomecollection.org/works/r3dhdzwq",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022498ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Six beetles including a stag beetle. Engraving by I. O. W.. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/six-beetles-stag-beetle.webp",
    "width": 1577,
    "height": 2400
  },
  {
    "id": "wellcome-insects-nine-scarabaeid-beetles-v1",
    "name": "Nine different scarabaeid beetles",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "beetle",
      "scarab",
      "insect",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Newton after James Barbut",
    "sourceUrl": "https://wellcomecollection.org/works/f5e2jkdf",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022511EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Nine different scarabaeid beetles. Engraving by J. Newton after James Barbut. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/nine-scarabaeid-beetles.webp",
    "width": 1733,
    "height": 2400
  },
  {
    "id": "wellcome-insects-six-different-beetles-v1",
    "name": "Six different beetles",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "beetle",
      "insect",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/e8ukhjfp",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022531/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Six different beetles. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/six-different-beetles.webp",
    "width": 2000,
    "height": 977
  },
  {
    "id": "wellcome-insects-medlar-butterfly-caterpillar-v1",
    "name": "A flowering branch of medlar with butterfly, chrysalis and caterpillar",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "butterfly",
      "caterpillar",
      "chrysalis",
      "medlar",
      "insect",
      "botanical",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Pass",
    "sourceUrl": "https://wellcomecollection.org/works/q295sczh",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044323EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A flowering branch of medlar with butterfly, chrysalis and caterpillar. Engraving by J. Pass. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-insects/medlar-butterfly-caterpillar.webp",
    "width": 1819,
    "height": 2400
  }
];
