/** Generated from Public Domain Mark Wellcome Collection marine life engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_MARINE_LIFE_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-marine-sea-urchin-starfish-octopus-v1",
    "name": "Above, an edible sea urchin, a star fish and a purple spantangus; below, a common octopus and a large cuttlefish",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "sea urchin",
      "starfish",
      "octopus",
      "cuttlefish",
      "marine life",
      "ocean",
      "engraving",
      "hand-colored",
      "beach",
      "coastal",
      "nautical",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Home Lizars",
    "sourceUrl": "https://wellcomecollection.org/works/shq844bv",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020779EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Above, an edible sea urchin, a star fish and a purple spantangus; below, a common octopus and a large cuttlefish. Engraving by William Home Lizars. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/sea-urchin-starfish-octopus.webp",
    "width": 1473,
    "height": 2400
  },
  {
    "id": "wellcome-marine-corals-narwhal-natural-history-v1",
    "name": "Reef building corals, a narwhal, a horseshoe crab, and other natural history subjects",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "coral",
      "narwhal",
      "horseshoe crab",
      "shells",
      "murex",
      "marine life",
      "ocean",
      "engraving",
      "hand-colored",
      "natural history",
      "coastal",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Heath",
    "sourceUrl": "https://wellcomecollection.org/works/ruf5kygq",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020671ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Reef building corals, a narwhal, a horseshoe crab, and other natural history subjects. Engraving by Heath. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/corals-narwhal-natural-history.webp",
    "width": 1869,
    "height": 2400
  },
  {
    "id": "wellcome-marine-coconut-crab-v1",
    "name": "A crustacean (crab)",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "crab",
      "crustacean",
      "marine life",
      "ocean",
      "engraving",
      "hand-colored",
      "beach",
      "coastal",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. L. D. Coutant after F. N. Bevallet",
    "sourceUrl": "https://wellcomecollection.org/works/ncsurw88",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022033/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A crustacean (crab). Engraving by J. L. D. Coutant after F. N. Bevallet. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/coconut-crab.webp",
    "width": 2000,
    "height": 2340
  },
  {
    "id": "wellcome-marine-anemone-starfish-aquarium-v1",
    "name": "A serpent-haired sea-anemone and three species of star-fish",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "sea anemone",
      "starfish",
      "marine life",
      "ocean",
      "wood engraving",
      "line art",
      "aquarium",
      "coastal",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/p43nchhh",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021973EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A serpent-haired sea-anemone and three species of star-fish. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/anemone-starfish-aquarium.webp",
    "width": 1397,
    "height": 2400
  },
  {
    "id": "wellcome-marine-marine-aquarium-anemones-v1",
    "name": "A marine aquarium furnished with sea-anemones, sea-cucumbers and starfish",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "sea anemone",
      "sea cucumber",
      "starfish",
      "marine life",
      "ocean",
      "wood engraving",
      "line art",
      "aquarium",
      "coastal",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/dp7jcx2h",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021974/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A marine aquarium furnished with sea-anemones, sea-cucumbers and starfish. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/marine-aquarium-anemones.webp",
    "width": 2000,
    "height": 1228
  },
  {
    "id": "wellcome-marine-variety-sea-anemones-v1",
    "name": "A variety of sea anemones on the ground of an aquarium",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "sea anemone",
      "marine life",
      "ocean",
      "wood engraving",
      "line art",
      "aquarium",
      "coastal",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/n6rnrbna",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021978/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A variety of sea anemones on the ground of an aquarium. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-marine-life/variety-sea-anemones.webp",
    "width": 2000,
    "height": 1338
  }
];
