/** Generated from Public Domain Mark Wellcome Collection 1775 embroidery-design engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_EMBROIDERY_SPRIGS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-lilies-carnations-auricula-v1",
    "name": "Two sprigs of flowers, including lilies, carnations and Auricula, meant as designs for embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "embroidery design",
      "floral",
      "botanical",
      "sprig",
      "engraving",
      "line art",
      "1775",
      "vintage",
      "textile design",
      "pattern reference",
      "craft gift",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Kilburn, 1775",
    "sourceUrl": "https://wellcomecollection.org/works/cqwy8xcd",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044077/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two sprigs of flowers, including lilies, carnations and Auricula, meant as designs for embroidery. Etching with engraving after William Kilburn, 1775. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-embroidery-sprigs/lilies-carnations-auricula.webp",
    "width": 2000,
    "height": 1414
  },
  {
    "id": "wellcome-tulip-honeysuckle-v1",
    "name": "Two sprigs of flowers, including tulip and honeysuckle, meant as designs for embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "embroidery design",
      "floral",
      "botanical",
      "sprig",
      "tulip",
      "honeysuckle",
      "engraving",
      "line art",
      "1775",
      "vintage",
      "textile design",
      "pattern reference",
      "craft gift",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Kilburn, 1775",
    "sourceUrl": "https://wellcomecollection.org/works/tjhcd6kq",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044075/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two sprigs of flowers, including tulip and honeysuckle, meant as designs for embroidery. Etching with engraving after William Kilburn, 1775. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-embroidery-sprigs/tulip-honeysuckle.webp",
    "width": 2000,
    "height": 1413
  },
  {
    "id": "wellcome-convolvulus-carnations-v1",
    "name": "Two sprigs of flowers, including Convolvulus and carnations, meant as designs for embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "embroidery design",
      "floral",
      "botanical",
      "sprig",
      "convolvulus",
      "carnation",
      "engraving",
      "line art",
      "1775",
      "vintage",
      "textile design",
      "pattern reference",
      "craft gift",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Dodd, 1775",
    "sourceUrl": "https://wellcomecollection.org/works/yvbzqfk6",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044078/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two sprigs of flowers, including Convolvulus and carnations, meant as designs for embroidery. Etching with engraving after Dodd, 1775. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-embroidery-sprigs/convolvulus-carnations.webp",
    "width": 2000,
    "height": 1294
  },
  {
    "id": "wellcome-roses-narcissi-v1",
    "name": "Two sprigs of flowers including roses and Narcissi, meant as designs for embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "embroidery design",
      "floral",
      "botanical",
      "sprig",
      "rose",
      "narcissus",
      "engraving",
      "line art",
      "1775",
      "vintage",
      "textile design",
      "pattern reference",
      "craft gift",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Kilburn, 1775",
    "sourceUrl": "https://wellcomecollection.org/works/ykvqwre9",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044074/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two sprigs of flowers including roses and Narcissi, meant as designs for embroidery. Etching with engraving after William Kilburn, 1775. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-embroidery-sprigs/roses-narcissi.webp",
    "width": 2000,
    "height": 1415
  },
  {
    "id": "wellcome-iris-narcissus-v1",
    "name": "Two sprigs of flowers, including iris and double Narcissus, meant as designs for embroidery",
    "kind": "element",
    "category": "Patterns",
    "tags": [
      "embroidery design",
      "floral",
      "botanical",
      "sprig",
      "iris",
      "narcissus",
      "engraving",
      "line art",
      "1775",
      "vintage",
      "textile design",
      "pattern reference",
      "craft gift",
      "sublimation"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Kilburn, 1775",
    "sourceUrl": "https://wellcomecollection.org/works/ruymcc9g",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044076/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two sprigs of flowers, including iris and double Narcissus, meant as designs for embroidery. Etching with engraving after William Kilburn, 1775. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-embroidery-sprigs/iris-narcissus.webp",
    "width": 2000,
    "height": 1358
  }
];
