/** Generated from Public Domain Mark Wellcome Collection fish and marine mammal engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_FISH_AND_MARINE_MAMMALS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-fish-marine-mammals-whale-dolphin-porpoise-v1",
    "name": "A common whale, a dolphin and a porpoise",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "whale",
      "dolphin",
      "porpoise",
      "marine mammal",
      "ocean",
      "sea",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — P. Dixon",
    "sourceUrl": "https://wellcomecollection.org/works/adg22vre",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021598/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A common whale, a dolphin and a porpoise. Illustration by P. Dixon. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/whale-dolphin-porpoise.webp",
    "width": 2000,
    "height": 1369
  },
  {
    "id": "wellcome-fish-marine-mammals-three-sharks-v1",
    "name": "Above, a lesser spotted shark; middle, a porbeagle; below, a white shark",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "shark",
      "fish",
      "ocean",
      "sea",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — W. H. Lizars",
    "sourceUrl": "https://wellcomecollection.org/works/zzk4887y",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020779ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Above, a lesser spotted shark; middle, a porbeagle; below, a white shark. Illustration by W. H. Lizars. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/three-sharks.webp",
    "width": 1460,
    "height": 2400
  },
  {
    "id": "wellcome-fish-marine-mammals-fish-swimming-in-sea-v1",
    "name": "A fish swimming in the sea",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "ocean",
      "sea",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Heath",
    "sourceUrl": "https://wellcomecollection.org/works/yebpuyrw",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021234/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A fish swimming in the sea. Illustration by J. Heath. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/fish-swimming-in-sea.webp",
    "width": 1505,
    "height": 2400
  },
  {
    "id": "wellcome-fish-marine-mammals-flying-fish-with-boat-v1",
    "name": "A flying fish in the sea with a boat in the background",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "flying fish",
      "ocean",
      "sea",
      "boat",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Whymper",
    "sourceUrl": "https://wellcomecollection.org/works/zdcdb3z4",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020511/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A flying fish in the sea with a boat in the background. Illustration by J. W. Whymper. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/flying-fish-with-boat.webp",
    "width": 2000,
    "height": 1629
  },
  {
    "id": "wellcome-fish-marine-mammals-flying-fish-and-enemies-v1",
    "name": "A flying fish and its enemies of the air and water, including an albatros and a dolphin",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "flying fish",
      "albatross",
      "dolphin",
      "ocean",
      "sea",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Basire",
    "sourceUrl": "https://wellcomecollection.org/works/j35234az",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022083/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A flying fish and its enemies of the air and water, including an albatros and a dolphin. Illustration by J. Basire. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/flying-fish-and-enemies.webp",
    "width": 1751,
    "height": 2400
  },
  {
    "id": "wellcome-fish-marine-mammals-flying-fish-chinese-seaport-v1",
    "name": "Above, a flying fish hovering over the sea; below, a Chinese village sea-port",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "flying fish",
      "seaport",
      "ocean",
      "sea",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Wood",
    "sourceUrl": "https://wellcomecollection.org/works/dkdn5bhe",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022823/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Above, a flying fish hovering over the sea; below, a Chinese village sea-port. Illustration by J. Wood. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/flying-fish-chinese-seaport.webp",
    "width": 1823,
    "height": 2400
  },
  {
    "id": "wellcome-fish-marine-mammals-swordfish-mid-air-v1",
    "name": "A swordfish suspended mid-air before a coastal scene",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "swordfish",
      "coastal",
      "ocean",
      "sea",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Whymper",
    "sourceUrl": "https://wellcomecollection.org/works/x2gqjhng",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020528/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A swordfish suspended mid-air before a coastal scene. Illustration by J. W. Whymper. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/swordfish-mid-air.webp",
    "width": 2000,
    "height": 1582
  },
  {
    "id": "wellcome-fish-marine-mammals-pike-walrus-manatee-v1",
    "name": "Top, two pike fish; bottom right, a walrus; bottom left, a manatee",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "fish",
      "pike",
      "walrus",
      "manatee",
      "marine mammal",
      "ocean",
      "sea",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Pass",
    "sourceUrl": "https://wellcomecollection.org/works/un4k82xr",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0048106EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Top, two pike fish; bottom right, a walrus; bottom left, a manatee. Illustration by J. Pass. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-fish-and-marine-mammals/pike-walrus-manatee.webp",
    "width": 1858,
    "height": 2400
  }
];
