/** Generated from Public Domain Mark Wellcome Collection tropical flora engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_TROPICAL_FLORA_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-tropical-flora-hibiscus-flowering-shoot-v1",
    "name": "China rose or Shoe flower (Hibiscus rosa-sinensis L.): flowering shoot",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "hibiscus",
      "flower",
      "tropical",
      "botanical",
      "plant",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/zr22kd3f",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0042667/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "China rose or Shoe flower (Hibiscus rosa-sinensis L.): flowering shoot. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/hibiscus-flowering-shoot.webp",
    "width": 2000,
    "height": 1542
  },
  {
    "id": "wellcome-tropical-flora-hibiscus-branch-fruit-seeds-v1",
    "name": "China rose or Shoe flower (Hibiscus rosa-sinensis L.): branch with flowers and fruit and separate flower, dissected fruit and seeds",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "hibiscus",
      "flower",
      "tropical",
      "botanical",
      "plant",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/hrrevd9y",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0042668/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "China rose or Shoe flower (Hibiscus rosa-sinensis L.): branch with flowers and fruit and separate flower, dissected fruit and seeds. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/hibiscus-branch-fruit-seeds.webp",
    "width": 2000,
    "height": 1640
  },
  {
    "id": "wellcome-tropical-flora-breadfruit-tree-landscape-v1",
    "name": "Breadfruit tree (Artocarpus altilis) in tropical landscape",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "breadfruit",
      "tree",
      "tropical",
      "botanical",
      "plant",
      "landscape",
      "island",
      "nature",
      "aquatint",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Daniell",
    "sourceUrl": "https://wellcomecollection.org/works/gjxq3xq4",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0043227/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Breadfruit tree (Artocarpus altilis) in tropical landscape. Illustration by William Daniell. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/breadfruit-tree-landscape.webp",
    "width": 2000,
    "height": 1427
  },
  {
    "id": "wellcome-tropical-flora-coconut-cinnamon-pinang-landscape-v1",
    "name": "Coconuts and trees (Cocos nucifera), a cinnamon tree (Cinnamomum verum) and pinang tree (Areca catechu), in a tropical landscape",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "coconut",
      "palm",
      "tree",
      "tropical",
      "botanical",
      "plant",
      "landscape",
      "island",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Johan Nieuhof",
    "sourceUrl": "https://wellcomecollection.org/works/fz2utq7p",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0043077/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Coconuts and trees (Cocos nucifera), a cinnamon tree (Cinnamomum verum) and pinang tree (Areca catechu), in a tropical landscape. Illustration by Johan Nieuhof. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/coconut-cinnamon-pinang-landscape.webp",
    "width": 2000,
    "height": 1575
  },
  {
    "id": "wellcome-tropical-flora-plantain-banana-sections-v1",
    "name": "Plantain banana (Musa x paradisiaca L.): nine sections of flower and fruit",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "banana",
      "plantain",
      "fruit",
      "tropical",
      "botanical",
      "plant",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — G. D. Ehret",
    "sourceUrl": "https://wellcomecollection.org/works/w8w9b59f",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0042994/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Plantain banana (Musa x paradisiaca L.): nine sections of flower and fruit. Illustration by G. D. Ehret. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/plantain-banana-sections.webp",
    "width": 1552,
    "height": 2400
  },
  {
    "id": "wellcome-tropical-flora-screwpine-lakeside-v1",
    "name": "Screwpine plants (Pandanus muricatus) on a lakeside",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "screwpine",
      "pandanus",
      "tropical",
      "botanical",
      "plant",
      "landscape",
      "island",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/f35m9nue",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0043200/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Screwpine plants (Pandanus muricatus) on a lakeside. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/screwpine-lakeside.webp",
    "width": 2000,
    "height": 1854
  },
  {
    "id": "wellcome-tropical-flora-screwpine-madagascar-tent-v1",
    "name": "Screwpine plants (Pandanus species) of Madagascar, sheltering a tent",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "screwpine",
      "pandanus",
      "tropical",
      "botanical",
      "plant",
      "landscape",
      "island",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/vgqwn83r",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0043199/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Screwpine plants (Pandanus species) of Madagascar, sheltering a tent. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/screwpine-madagascar-tent.webp",
    "width": 2000,
    "height": 2349
  },
  {
    "id": "wellcome-tropical-flora-banana-plants-date-palm-v1",
    "name": "Two banana plants (Musa species) and a date palm tree",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "banana",
      "palm",
      "tree",
      "tropical",
      "botanical",
      "plant",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/h6scejp4",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044737/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two banana plants (Musa species) and a date palm tree. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-tropical-flora/banana-plants-date-palm.webp",
    "width": 1838,
    "height": 2400
  }
];
