/** Generated from Public Domain Mark Wellcome Collection botanical engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_BOTANICAL_PLATES_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-botanical-yellow-iris-v1",
    "name": "A yellow iris (Iris variegata): flower and leaf",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "iris",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "garden gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — James Sowerby",
    "sourceUrl": "https://wellcomecollection.org/works/zw9wukd2",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044362/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A yellow iris (Iris variegata): flower and leaf. Coloured engraving after James Sowerby, c. 1787. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/yellow-iris.webp",
    "width": 1425,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-houseleek-sempervivum-v1",
    "name": "A houseleek (Sempervivum arachnoideum): flowering plant",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "houseleek",
      "succulent",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "garden gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/a2v5cb84",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044363/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A houseleek (Sempervivum arachnoideum): flowering plant. Coloured engraving after William Curtis, c. 1788. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/houseleek-sempervivum.webp",
    "width": 1454,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-sunflower-helianthus-v1",
    "name": "Sunflower (Helianthus giganteus L.): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "sunflower",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "summer",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Franz Anton von Scheidl (attributed engraving)",
    "sourceUrl": "https://wellcomecollection.org/works/tzgdhxm8",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0042903ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Sunflower (Helianthus giganteus L.): flowering stem. Coloured engraving after Franz Anton von Scheidl (attributed engraving), 1772-era. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/sunflower-helianthus.webp",
    "width": 1474,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-anemone-v1",
    "name": "Anemone plant: flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "anemone",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "garden gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Johann Michael Seligmann",
    "sourceUrl": "https://wellcomecollection.org/works/jgahzs34",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0043099/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Anemone plant: flowering stem. Coloured engraving after Johann Michael Seligmann, c. 1768. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/anemone.webp",
    "width": 1522,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-statice-limonium-v1",
    "name": "Statice (Limonium sinuatum): flowering stem and leaf",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "statice",
      "sea lavender",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/zr8ze2nz",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044365ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Statice (Limonium sinuatum): flowering stem and leaf. Coloured engraving after William Curtis, c. 1789. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/statice-limonium.webp",
    "width": 1528,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-pelargonium-glaucum-v1",
    "name": "A pelargonium (Pelargonium glaucum): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "pelargonium",
      "geranium",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "garden gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Henry Cranke Andrews",
    "sourceUrl": "https://wellcomecollection.org/works/dhxg9j4x",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044353ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A pelargonium (Pelargonium glaucum): flowering stem. Coloured engraving after Henry Cranke Andrews, c. 1806. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/pelargonium-glaucum.webp",
    "width": 1613,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-mesembryanthemum-barbatum-v1",
    "name": "A plant (Mesembryanthemum barbatum): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "mesembryanthemum",
      "ice plant",
      "succulent",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/v3qm98rf",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044365EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A plant (Mesembryanthemum barbatum): flowering stem. Coloured engraving after William Curtis, c. 1789. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/mesembryanthemum-barbatum.webp",
    "width": 1444,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-christs-thorn-v1",
    "name": "Christ's thorn plant (Ziziphus spina-christi): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "christs thorn",
      "ziziphus",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "faith gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/emrutpjh",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044378ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Christ's thorn plant (Ziziphus spina-christi): flowering stem. Coloured engraving after William Curtis, c. 1817. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/christs-thorn.webp",
    "width": 1505,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-wild-plum-v1",
    "name": "Wild plum (Pappea capensis): flowering and fruiting stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "wild plum",
      "botanical illustration",
      "fruit",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "kitchen gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/gy6jd7db",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044361/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Wild plum (Pappea capensis): flowering and fruiting stem. Coloured engraving after William Curtis, c. 1792. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/wild-plum.webp",
    "width": 1512,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-night-flowering-catchfly-v1",
    "name": "Night-flowering catchfly (Silene noctiflorum): flowering stem and floral segments",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "catchfly",
      "silene",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — James Sowerby",
    "sourceUrl": "https://wellcomecollection.org/works/ctf3fwuq",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044207ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Night-flowering catchfly (Silene noctiflorum): flowering stem and floral segments. Coloured engraving after James Sowerby, unknown. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/night-flowering-catchfly.webp",
    "width": 1404,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-polygonum-orientale-v1",
    "name": "A plant (Polygonum orientale): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "polygonum",
      "kiss-me-over-the-garden-gate",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/g7nkbj2s",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044367ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A plant (Polygonum orientale): flowering stem. Coloured engraving after William Curtis, c. 1792. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/polygonum-orientale.webp",
    "width": 1362,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-peperomia-acuminata-v1",
    "name": "A plant (Peperomia acuminata): flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "peperomia",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "houseplant gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/ug3buc7t",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044378EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A plant (Peperomia acuminata): flowering stem. Coloured engraving after William Curtis, c. 1817. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/peperomia-acuminata.webp",
    "width": 1451,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-fumitory-v1",
    "name": "Fumitory (Fumaria glauca): flowering and fruiting stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "fumitory",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "wildflower",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/e5tcg5s8",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044366ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Fumitory (Fumaria glauca): flowering and fruiting stem. Coloured engraving after William Curtis, c. 1792. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/fumitory.webp",
    "width": 1510,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-inula-viscosa-v1",
    "name": "Inula viscosa: flowering stem",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "inula",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "wildflower",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Franz Anton von Scheidl (attributed engraving)",
    "sourceUrl": "https://wellcomecollection.org/works/bpep4y2d",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0042905ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Inula viscosa: flowering stem. Coloured engraving after Franz Anton von Scheidl (attributed engraving), 1772-era. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/inula-viscosa.webp",
    "width": 1142,
    "height": 2400
  },
  {
    "id": "wellcome-botanical-monsonia-speciosa-v1",
    "name": "A plant (Monsonia speciosa): flowering stem and leaf",
    "kind": "element",
    "category": "Botanical",
    "tags": [
      "monsonia",
      "botanical illustration",
      "flower",
      "engraving",
      "hand-colored",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — William Curtis",
    "sourceUrl": "https://wellcomecollection.org/works/a3mq2236",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044366EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A plant (Monsonia speciosa): flowering stem and leaf. Coloured engraving after William Curtis, c. 1789. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-botanical-plates/monsonia-speciosa.webp",
    "width": 1390,
    "height": 2400
  }
];
