/** Generated from Public Domain Mark Wellcome Collection fungi/lichen/moss engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_CRYPTOGAMS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-cryptogams-mushroom-varieties-v1",
    "name": "Varieties of mushrooms and edible fungi (comparative chart)",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "mushroom",
      "fungi",
      "toadstool",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "kitchen gift",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — Aristide-Michel Perrot after E. Hocquart and J. C. Perrot",
    "sourceUrl": "https://wellcomecollection.org/works/p862u7gt",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0025758/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Varieties of mushrooms and edible fungi (comparative chart). Engraving by Aristide-Michel Perrot after E. Hocquart and J. C. Perrot. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/mushroom-varieties.webp",
    "width": 2000,
    "height": 1558
  },
  {
    "id": "wellcome-cryptogams-poisonous-plants-fly-agaric-v1",
    "name": "Four poisonous plants including fly agaric fungus",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "fly agaric",
      "mushroom",
      "fungi",
      "foxglove",
      "hellebore",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Johnstone",
    "sourceUrl": "https://wellcomecollection.org/works/gfkfxr9b",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044746/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Four poisonous plants including fly agaric fungus. Engraving by J. Johnstone. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/poisonous-plants-fly-agaric.webp",
    "width": 1435,
    "height": 2400
  },
  {
    "id": "wellcome-cryptogams-four-lichens-v1",
    "name": "Four types of lichen (Parmelia species)",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "lichen",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Pass",
    "sourceUrl": "https://wellcomecollection.org/works/uc9y9cy5",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044318/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Four types of lichen (Parmelia species). Engraving by J. Pass. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/four-lichens.webp",
    "width": 1866,
    "height": 2400
  },
  {
    "id": "wellcome-cryptogams-two-lichens-sectioned-v1",
    "name": "Two lichens with whole and sectioned thallus",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "lichen",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — James Sowerby",
    "sourceUrl": "https://wellcomecollection.org/works/h8zgkbt8",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044192EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Two lichens with whole and sectioned thallus. Engraving by James Sowerby. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/two-lichens-sectioned.webp",
    "width": 1409,
    "height": 2400
  },
  {
    "id": "wellcome-cryptogams-haircap-moss-v1",
    "name": "Six types of haircap moss (Polytrichum species)",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "moss",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Pass",
    "sourceUrl": "https://wellcomecollection.org/works/nj88nquj",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044314ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Six types of haircap moss (Polytrichum species). Engraving by J. Pass. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/haircap-moss.webp",
    "width": 1748,
    "height": 2400
  },
  {
    "id": "wellcome-cryptogams-bryum-moss-v1",
    "name": "A moss (Bryum calcareum), growth cycle",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "moss",
      "botanical illustration",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — James Sowerby",
    "sourceUrl": "https://wellcomecollection.org/works/qbfsj95s",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044178EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A moss (Bryum calcareum), growth cycle. Engraving by James Sowerby. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/bryum-moss.webp",
    "width": 1377,
    "height": 2400
  },
  {
    "id": "wellcome-cryptogams-neckera-moss-beetles-v1",
    "name": "Three mosses (Neckera species) with carrion beetles",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "moss",
      "beetle",
      "botanical illustration",
      "entomology",
      "engraving",
      "hand-colored",
      "nature",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Pass",
    "sourceUrl": "https://wellcomecollection.org/works/cb4rf6dm",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0044320ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "Three mosses (Neckera species) with carrion beetles. Engraving by J. Pass. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-cryptogams/neckera-moss-beetles.webp",
    "width": 1886,
    "height": 2400
  }
];
