/** Generated from Public Domain Mark Wellcome Collection shell/conchology engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_SHELLS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-shells-shells-table-105-v1",
    "name": "A table with 105 different shells",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "shells",
      "conchology",
      "seashell",
      "marine life",
      "ocean",
      "engraving",
      "line art",
      "coastal",
      "nautical",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — R. Scott after Captain T. Brown",
    "sourceUrl": "https://wellcomecollection.org/works/aprq82su",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020482EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A table with 105 different shells. Engraving by R. Scott after Captain T. Brown. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-shells/shells-table-105.webp",
    "width": 1522,
    "height": 2400
  },
  {
    "id": "wellcome-shells-shells-table-79-v1",
    "name": "A table with 79 different shells",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "shells",
      "conchology",
      "seashell",
      "marine life",
      "ocean",
      "engraving",
      "line art",
      "coastal",
      "nautical",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — R. Scott after Captain T. Brown",
    "sourceUrl": "https://wellcomecollection.org/works/xypmd3ay",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020482ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A table with 79 different shells. Engraving by R. Scott after Captain T. Brown. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-shells/shells-table-79.webp",
    "width": 1515,
    "height": 2400
  },
  {
    "id": "wellcome-shells-shells-table-163-v1",
    "name": "A table with 163 different shells (Organic Remains)",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "shells",
      "conchology",
      "seashell",
      "fossil",
      "marine life",
      "ocean",
      "engraving",
      "line art",
      "coastal",
      "nautical",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — R. Scott after Captain T. Brown",
    "sourceUrl": "https://wellcomecollection.org/works/cf8p5874",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020487ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A table with 163 different shells (Organic Remains). Engraving by R. Scott after Captain T. Brown. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-shells/shells-table-163.webp",
    "width": 1496,
    "height": 2400
  },
  {
    "id": "wellcome-shells-heart-shaped-shells-v1",
    "name": "A variety of heart-shaped shells (conche cordiformes)",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "shells",
      "conchology",
      "seashell",
      "cockle",
      "marine life",
      "ocean",
      "engraving",
      "line art",
      "coastal",
      "nautical",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/pze62svc",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021999/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A variety of heart-shaped shells (conche cordiformes). Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-shells/heart-shaped-shells.webp",
    "width": 1453,
    "height": 2400
  }
];
