/** Generated from Public Domain Mark Wellcome Collection bird engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_BIRDS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-birds-cockatoo-on-branch-v1",
    "name": "A cockatoo sitting on the branch of a tree",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "cockatoo",
      "parrot",
      "tropical",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — S. T. Edwards after A. Latham",
    "sourceUrl": "https://wellcomecollection.org/works/h9fqdzka",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022861ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A cockatoo sitting on the branch of a tree. Illustration by S. T. Edwards after A. Latham. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/cockatoo-on-branch.webp",
    "width": 1803,
    "height": 2400
  },
  {
    "id": "wellcome-birds-parrot-rainforest-v1",
    "name": "A parrot sitting on a branch of a tree in the rainforest",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "parrot",
      "tropical",
      "rainforest",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Whymper",
    "sourceUrl": "https://wellcomecollection.org/works/zpf8unnx",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020531/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A parrot sitting on a branch of a tree in the rainforest. Illustration by J. W. Whymper. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/parrot-rainforest.webp",
    "width": 1858,
    "height": 2400
  },
  {
    "id": "wellcome-birds-common-tropic-bird-v1",
    "name": "A common tropic bird",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "tropic bird",
      "seabird",
      "ocean",
      "tropical",
      "island",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/bugqbr9d",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022254ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A common tropic bird. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/common-tropic-bird.webp",
    "width": 1607,
    "height": 2400
  },
  {
    "id": "wellcome-birds-racket-tailed-kingfisher-v1",
    "name": "A bird, possibly a raquet-tailed kingfisher",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "kingfisher",
      "tropical",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/zfv92kz2",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022372EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A bird, possibly a raquet-tailed kingfisher. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/racket-tailed-kingfisher.webp",
    "width": 2000,
    "height": 1375
  },
  {
    "id": "wellcome-birds-kingfisher-on-stump-v1",
    "name": "A kingfisher sitting on a stump of a tree",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "kingfisher",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — P. Mazell",
    "sourceUrl": "https://wellcomecollection.org/works/vavkda2g",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022864ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A kingfisher sitting on a stump of a tree. Illustration by P. Mazell. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/kingfisher-on-stump.webp",
    "width": 1777,
    "height": 2400
  },
  {
    "id": "wellcome-birds-common-heron-v1",
    "name": "A common heron",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "heron",
      "wading bird",
      "coastal",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/m9akhf4v",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022242ER/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A common heron. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/common-heron.webp",
    "width": 1641,
    "height": 2400
  },
  {
    "id": "wellcome-birds-swallow-in-flight-v1",
    "name": "A swallow sitting on a rock above a town with two other swallows flying in the sky above",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "swallow",
      "flight",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Whymper",
    "sourceUrl": "https://wellcomecollection.org/works/pum4thqp",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020517/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A swallow sitting on a rock above a town with two other swallows flying in the sky above. Illustration by J. W. Whymper. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/swallow-in-flight.webp",
    "width": 2000,
    "height": 1666
  },
  {
    "id": "wellcome-birds-night-heron-v1",
    "name": "A night heron",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "bird",
      "heron",
      "wading bird",
      "coastal",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/bzddxua8",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022244EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A night heron. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-birds/night-heron.webp",
    "width": 1652,
    "height": 2400
  }
];
