/** Generated from Public Domain Mark Wellcome Collection reptile/amphibian engravings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WELLCOME_REPTILES_AMPHIBIANS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wellcome-reptiles-amphibians-edible-frog-tadpole-v1",
    "name": "The edible frog with tadpole, tree frog with tadpole and horned frog",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "frog",
      "tadpole",
      "amphibian",
      "reptile",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Lowry after C. Bone",
    "sourceUrl": "https://wellcomecollection.org/works/zate8uc2",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022773EL/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "The edible frog with tadpole, tree frog with tadpole and horned frog. Illustration by J. W. Lowry after C. Bone. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/edible-frog-tadpole.webp",
    "width": 1635,
    "height": 2400
  },
  {
    "id": "wellcome-reptiles-amphibians-bull-frog-v1",
    "name": "A bull frog",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "frog",
      "amphibian",
      "reptile",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. Heath",
    "sourceUrl": "https://wellcomecollection.org/works/zjhtrdjh",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0021245/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A bull frog. Illustration by J. Heath. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/bull-frog.webp",
    "width": 2000,
    "height": 1429
  },
  {
    "id": "wellcome-reptiles-amphibians-laced-lizard-australia-v1",
    "name": "A laced lizard in Australia",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "lizard",
      "reptile",
      "australia",
      "nature",
      "etching",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — S. T. Edwards",
    "sourceUrl": "https://wellcomecollection.org/works/wp5z86uw",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022868/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A laced lizard in Australia. Illustration by S. T. Edwards. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/laced-lizard-australia.webp",
    "width": 2000,
    "height": 1496
  },
  {
    "id": "wellcome-reptiles-amphibians-lizard-on-stone-v1",
    "name": "A lizard sitting on a stone",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "lizard",
      "reptile",
      "nature",
      "wood engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — J. W. Whymper",
    "sourceUrl": "https://wellcomecollection.org/works/xffxxs7d",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0020515/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A lizard sitting on a stone. Illustration by J. W. Whymper. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/lizard-on-stone.webp",
    "width": 1907,
    "height": 2400
  },
  {
    "id": "wellcome-reptiles-amphibians-snake-expanded-neck-v1",
    "name": "A snake with expanded neck",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "snake",
      "cobra",
      "reptile",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/z6v69rju",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022457/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A snake with expanded neck. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/snake-expanded-neck.webp",
    "width": 2000,
    "height": 1276
  },
  {
    "id": "wellcome-reptiles-amphibians-indian-snake-bodroo-pam-v1",
    "name": "An Indian snake, Bodroo Pam",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "snake",
      "reptile",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — W. Skelton after Patrick Russell",
    "sourceUrl": "https://wellcomecollection.org/works/am2wj2s7",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022452/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "An Indian snake, Bodroo Pam. Illustration by W. Skelton after Patrick Russell. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/indian-snake-bodroo-pam.webp",
    "width": 2000,
    "height": 973
  },
  {
    "id": "wellcome-reptiles-amphibians-indian-boa-snake-v1",
    "name": "An Indian snake of the Boa genus, Gedi Paragoodoo",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "snake",
      "boa",
      "reptile",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — W. Skelton after Patrick Russell",
    "sourceUrl": "https://wellcomecollection.org/works/y9ufz8dh",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022453/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "An Indian snake of the Boa genus, Gedi Paragoodoo. Illustration by W. Skelton after Patrick Russell. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/indian-boa-snake.webp",
    "width": 2000,
    "height": 1252
  },
  {
    "id": "wellcome-reptiles-amphibians-horned-viper-v1",
    "name": "A horned viper",
    "kind": "element",
    "category": "Nature",
    "tags": [
      "snake",
      "viper",
      "reptile",
      "nature",
      "engraving",
      "line art",
      "natural history",
      "sublimation",
      "print decoration",
      "POD design"
    ],
    "license": "Creative Commons Public Domain Mark 1.0",
    "source": "Wellcome Collection — unattributed",
    "sourceUrl": "https://wellcomecollection.org/works/f72jqpv3",
    "evidenceUrl": "https://iiif.wellcomecollection.org/image/V0022456/info.json",
    "licenseId": "PUBLIC-DOMAIN-MARK-1.0",
    "licenseUrl": "http://creativecommons.org/publicdomain/mark/1.0/",
    "attributionRequired": false,
    "attributionText": "A horned viper. Creator not identified in the collection record. Credit: Wellcome Collection. Public Domain Mark.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wellcome-reptiles-amphibians/horned-viper.webp",
    "width": 2000,
    "height": 995
  }
];
