/** Generated from public-domain Wikimedia Commons Victorian trade card ephemera. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WIKIMEDIA_VICTORIAN_TRADE_CARDS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wikimedia-trade-cards-christmas-robin-v1",
    "name": "Victorian Christmas robin trade card",
    "kind": "element",
    "category": "Celebrations",
    "tags": [
      "victorian",
      "christmas",
      "trade card",
      "robin",
      "chromolithograph",
      "vintage",
      "holiday",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Victorian_Christmas_Trade_Card.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Victorian_Christmas_Trade_Card.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Victorian Christmas robin trade card, chromolithograph, late 19th century. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/victorian-christmas-robin.webp",
    "width": 1281,
    "height": 837
  },
  {
    "id": "wikimedia-trade-cards-hummingbird-christmas-v1",
    "name": "Hummingbird Christmas trade card",
    "kind": "element",
    "category": "Celebrations",
    "tags": [
      "victorian",
      "christmas",
      "trade card",
      "hummingbird",
      "bird",
      "chromolithograph",
      "vintage",
      "holiday",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hummingbird_Christmas_trade_card_-_circa_1890s.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Hummingbird_Christmas_trade_card_-_circa_1890s.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Hummingbird Christmas trade card, chromolithograph, circa 1890s. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/hummingbird-christmas.webp",
    "width": 1733,
    "height": 900
  },
  {
    "id": "wikimedia-trade-cards-die-cut-hand-fan-v1",
    "name": "Die-cut Victorian hand fan advertising card",
    "kind": "element",
    "category": "Decorative elements",
    "tags": [
      "victorian",
      "trade card",
      "die-cut",
      "hand fan",
      "chromolithograph",
      "vintage",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Die-cut_Victorian_hand_fan_advertising_card.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Die-cut_Victorian_hand_fan_advertising_card.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Die-cut Victorian hand fan advertising card, chromolithograph, late 19th century. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/die-cut-hand-fan.webp",
    "width": 1319,
    "height": 1871
  },
  {
    "id": "wikimedia-trade-cards-lea-perrins-v1",
    "name": "Lea & Perrins' Sauce trade card",
    "kind": "element",
    "category": "Decorative elements",
    "tags": [
      "victorian",
      "trade card",
      "advertising",
      "chromolithograph",
      "vintage",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lea_%26_Perrins%27_Sauce_trade_card_front.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Lea_%26_Perrins%27_Sauce_trade_card_front.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Lea & Perrins' Sauce trade card, chromolithograph, late 19th century. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/lea-perrins-sauce.webp",
    "width": 1013,
    "height": 1500
  },
  {
    "id": "wikimedia-trade-cards-fishing-party-v1",
    "name": "Waiting for the fishing party trade card",
    "kind": "element",
    "category": "Decorative elements",
    "tags": [
      "victorian",
      "trade card",
      "fishing",
      "genre scene",
      "chromolithograph",
      "vintage",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Waiting_for_the_fishing_party-front-_trade_card.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Waiting_for_the_fishing_party-front-_trade_card.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "\"Waiting for the fishing party\" trade card, chromolithograph, late 19th century. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/fishing-party.webp",
    "width": 811,
    "height": 1500
  },
  {
    "id": "wikimedia-trade-cards-ornate-border-dentist-v1",
    "name": "Ornate Victorian business card border (dentist)",
    "kind": "element",
    "category": "Frames",
    "tags": [
      "victorian",
      "trade card",
      "ornamental border",
      "frame",
      "scrollwork",
      "vintage",
      "ephemera",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — unattributed",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Print,_trade-card_(BM_1983,U.175).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Print,_trade-card_(BM_1983,U.175).jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Ornate Victorian business card border, 19th century. Credit: British Museum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-victorian-trade-cards/ornate-border-dentist.webp",
    "width": 1030,
    "height": 1600
  }
];
