/** Generated from Wikimedia Commons "No known copyright restrictions" ornamental alphabet plates (1898). Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WIKIMEDIA_ORNAMENTAL_ALPHABETS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wikimedia-ornamental-alphabets-ornamental-caps-v1",
    "name": "Ornamental flourished capitals",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "ornamental",
      "flourish",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579317108).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579317108).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Ornamental flourished capitals, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/ornamental-caps-dchklmnpstsz.webp",
    "width": 1401,
    "height": 2400
  },
  {
    "id": "wikimedia-ornamental-alphabets-hatched-pattern-v1",
    "name": "Hatched pattern-fill capitals",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "hatched",
      "pattern",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14765652312).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14765652312).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Hatched pattern-fill capitals, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/hatched-pattern-caps.webp",
    "width": 1530,
    "height": 2400
  },
  {
    "id": "wikimedia-ornamental-alphabets-roman-serif-v1",
    "name": "Roman serif alphabet with grid guide",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "roman",
      "serif",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579193090).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579193090).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Roman serif alphabet with grid guide, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/roman-serif-grid.webp",
    "width": 1445,
    "height": 2400
  },
  {
    "id": "wikimedia-ornamental-alphabets-gothic-banner-v1",
    "name": "Gothic blackletter banner alphabet",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "gothic",
      "blackletter",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579337009).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14579337009).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Gothic blackletter banner alphabet, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/gothic-blackletter-banner.webp",
    "width": 1664,
    "height": 1940
  },
  {
    "id": "wikimedia-ornamental-alphabets-bold-roman-v1",
    "name": "Bold white-on-black Roman capitals",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "roman",
      "bold",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14742892316).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14742892316).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Bold white-on-black Roman capitals, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/bold-white-on-black-roman.webp",
    "width": 1708,
    "height": 1936
  },
  {
    "id": "wikimedia-ornamental-alphabets-illuminated-initials-v1",
    "name": "Illuminated initial letters in decorative frames",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "illuminated",
      "initial letter",
      "ornamental",
      "hand lettering",
      "calligraphy",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14763556974).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14763556974).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Illuminated initial letters in decorative frames, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/illuminated-initial-cells.webp",
    "width": 1828,
    "height": 1312
  },
  {
    "id": "wikimedia-ornamental-alphabets-flourished-script-v1",
    "name": "Ornate flourished script capitals",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "script",
      "flourish",
      "calligraphy",
      "hand lettering",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14763564164).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14763564164).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Ornate flourished script capitals, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/ornate-flourished-script.webp",
    "width": 1678,
    "height": 2400
  },
  {
    "id": "wikimedia-ornamental-alphabets-geometric-angular-v1",
    "name": "Geometric angular block capitals",
    "kind": "element",
    "category": "Typography & Lettering",
    "tags": [
      "alphabet",
      "lettering",
      "typography",
      "geometric",
      "angular",
      "block letters",
      "hand lettering",
      "design reference",
      "sublimation"
    ],
    "license": "No restrictions",
    "source": "Wikimedia Commons — Lewis Foreman Day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14765977695).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Alphabets_old_and_new,_for_the_use_of_craftsmen_-_with_an_introductory_essay_on_Art_in_the_alphabet_(1898)_(14765977695).jpg",
    "licenseId": "NKCR",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "attributionRequired": false,
    "attributionText": "Geometric angular block capitals, from Lewis Foreman Day, \"Alphabets Old and New\" (London: Batsford, 1898). Credit: Internet Archive Book Images, via Wikimedia Commons. No known copyright restrictions.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-ornamental-alphabets/geometric-angular-caps.webp",
    "width": 1490,
    "height": 2400
  }
];
