/** Generated from public-domain Wikimedia Commons historical Pacific nautical charts. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WIKIMEDIA_PACIFIC_CHARTS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "admiralty-chart-970",
    "name": "1929 Admiralty chart: Caroline Islands anchorages",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Caroline Islands",
      "Chuuk",
      "Namonuito",
      "Hall Islands",
      "Micronesia",
      "Pacific",
      "1929",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — United Kingdom Hydrographic Office",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_970_Islands_and_Anchorages_in_the_Caroline_Islands,_Published_1929.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_970_Islands_and_Anchorages_in_the_Caroline_Islands,_Published_1929.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Scan of original Admiralty Chart No. 970, United Kingdom Hydrographic Office, 1929. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/admiralty-chart-970.webp",
    "width": 2400,
    "height": 1637
  },
  {
    "id": "albatross-track-1900",
    "name": "1900 chart: Pohnpei to Guam through the Carolines",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Pohnpei",
      "Ponapi",
      "Chuuk",
      "Truk",
      "Guam",
      "Caroline Islands",
      "Micronesia",
      "Pacific",
      "1900",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "expedition",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Alexander Agassiz (USFC Steamer Albatross expedition)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Track_of_the_Albatross_from_Pohnpei_through_the_Caroline_Islands_to_Guam_in_February_1900_(map0027541873).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Track_of_the_Albatross_from_Pohnpei_through_the_Caroline_Islands_to_Guam_in_February_1900_(map0027541873).jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "USFC Steamer Albatross expedition chart, Alexander Agassiz, 1900. Source: NOAA Photo Library. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/albatross-track-1900.webp",
    "width": 2400,
    "height": 1923
  }
];
