/** Generated from public-domain Wikimedia Commons Dutch Golden Age maritime paintings. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WIKIMEDIA_DUTCH_MARITIME_PAINTINGS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "wikimedia-dutch-maritime-turbulent-sea-v1",
    "name": "Turbulent sea with ships",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "ocean",
      "sea",
      "storm",
      "waves",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Ludolf Bakhuizen",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Woelige_zee_met_schepen_Rijksmuseum_SK-A-2315.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Woelige_zee_met_schepen_Rijksmuseum_SK-A-2315.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Turbulent sea with ships, Ludolf Bakhuizen, 1697. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/turbulent-sea-with-ships.webp",
    "width": 2400,
    "height": 1930
  },
  {
    "id": "wikimedia-dutch-maritime-het-ij-frigate-v1",
    "name": "The IJ at Amsterdam with the frigate De Ploeg",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "frigate",
      "harbor",
      "ocean",
      "sea",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Ludolf Bakhuizen",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Het_IJ_voor_Amsterdam_met_het_fregat_%27De_Ploeg%27._Rijksmuseum_SK-C-91.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Het_IJ_voor_Amsterdam_met_het_fregat_%27De_Ploeg%27._Rijksmuseum_SK-C-91.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "The IJ at Amsterdam with the frigate 'De Ploeg', Ludolf Bakhuizen, 1690. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/het-ij-frigate-de-ploeg.webp",
    "width": 2400,
    "height": 1949
  },
  {
    "id": "wikimedia-dutch-maritime-ijselmonde-v1",
    "name": "Ships before IJselmonde",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "ocean",
      "sea",
      "coast",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Aert Anthoniszoon",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_voor_IJselmonde_Rijksmuseum_SK-A-1446.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_voor_IJselmonde_Rijksmuseum_SK-A-1446.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Ships before IJselmonde, Aert Anthoniszoon, 1617. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/ships-before-ijselmonde.webp",
    "width": 2400,
    "height": 1186
  },
  {
    "id": "wikimedia-dutch-maritime-roadstead-texel-v1",
    "name": "Dutch ships in the roadstead of Texel",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "fleet",
      "flagship",
      "ocean",
      "sea",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Ludolf Bakhuizen",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nederlandse_schepen_op_de_rede_van_Texel;_in_het_midden_de_%27Gouden_Leeuw%27,_het_vlaggeschip_van_Cornelis_Tromp_Rijksmuseum_SK-A-8.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Nederlandse_schepen_op_de_rede_van_Texel;_in_het_midden_de_%27Gouden_Leeuw%27,_het_vlaggeschip_van_Cornelis_Tromp_Rijksmuseum_SK-A-8.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Dutch ships in the roadstead of Texel, Ludolf Bakhuizen, 1671. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/dutch-ships-roadstead-texel.webp",
    "width": 2400,
    "height": 1576
  },
  {
    "id": "wikimedia-dutch-maritime-men-o-war-calm-v1",
    "name": "Dutch men-o'-war and other shipping in a calm",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "warship",
      "calm sea",
      "ocean",
      "sea",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Willem van de Velde the Younger",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Willem_van_de_Velde_II_-_Dutch_men-o%27-war_and_other_shipping_in_a_calm.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Willem_van_de_Velde_II_-_Dutch_men-o%27-war_and_other_shipping_in_a_calm.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Dutch men-o'-war and other shipping in a calm, Willem van de Velde the Younger, circa 1665. Credit: Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/men-o-war-shipping-in-a-calm.webp",
    "width": 2400,
    "height": 1740
  },
  {
    "id": "wikimedia-dutch-maritime-off-the-coast-v1",
    "name": "Ships off the coast",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "ocean",
      "sea",
      "coast",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Adam Willaerts",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_voor_de_kust_Rijksmuseum_SK-A-1430.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_voor_de_kust_Rijksmuseum_SK-A-1430.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Ships off the coast, Adam Willaerts, 1628. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/ships-off-the-coast.webp",
    "width": 2400,
    "height": 1279
  },
  {
    "id": "wikimedia-dutch-maritime-warships-storm-v1",
    "name": "Warships in a storm",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "warship",
      "storm",
      "ocean",
      "sea",
      "waves",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Ludolf Bakhuizen",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oorlogsschepen_tijdens_een_storm_Rijksmuseum_SK-A-4856.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Oorlogsschepen_tijdens_een_storm_Rijksmuseum_SK-A-4856.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Warships in a storm, Ludolf Bakhuizen, 1695. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/warships-in-a-storm.webp",
    "width": 2400,
    "height": 1581
  },
  {
    "id": "wikimedia-dutch-maritime-rocky-coast-v1",
    "name": "Ships near a rocky coast",
    "kind": "element",
    "category": "Ocean & Nautical",
    "tags": [
      "ship",
      "sailing ship",
      "ocean",
      "sea",
      "rocky coast",
      "maritime",
      "painting",
      "Dutch Golden Age",
      "nautical",
      "sublimation"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Adam Willaerts",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_bij_een_rotsachtige_kust_Rijksmuseum_SK-A-1927.jpeg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Schepen_bij_een_rotsachtige_kust_Rijksmuseum_SK-A-1927.jpeg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Ships near a rocky coast, Adam Willaerts, 1621. Credit: Rijksmuseum, via Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-dutch-maritime-paintings/ships-near-rocky-coast.webp",
    "width": 2400,
    "height": 1189
  }
];
