/** Generated from public-domain and CC BY-SA Wikimedia Commons Micronesian/Pacific nautical charts and maps. Raster images, not vector. */
import type { StudioAsset } from "./asset-library";

export const WIKIMEDIA_PACIFIC_CHARTS_STUDIO_ASSETS: readonly StudioAsset[] = [
  {
    "id": "admiralty-chart-970",
    "name": "1929 Admiralty chart: Caroline Islands anchorages",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Caroline Islands",
      "Chuuk",
      "Namonuito",
      "Hall Islands",
      "Micronesia",
      "Pacific",
      "1929",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — United Kingdom Hydrographic Office",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_970_Islands_and_Anchorages_in_the_Caroline_Islands,_Published_1929.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_970_Islands_and_Anchorages_in_the_Caroline_Islands,_Published_1929.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Scan of original Admiralty Chart No. 970, United Kingdom Hydrographic Office, 1929. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/admiralty-chart-970.webp",
    "width": 2400,
    "height": 1637
  },
  {
    "id": "albatross-track-1900",
    "name": "1900 chart: Pohnpei to Guam through the Carolines",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Pohnpei",
      "Ponapi",
      "Chuuk",
      "Truk",
      "Guam",
      "Caroline Islands",
      "Micronesia",
      "Pacific",
      "1900",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "expedition",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Alexander Agassiz (USFC Steamer Albatross expedition)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Track_of_the_Albatross_from_Pohnpei_through_the_Caroline_Islands_to_Guam_in_February_1900_(map0027541873).jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Track_of_the_Albatross_from_Pohnpei_through_the_Caroline_Islands_to_Guam_in_February_1900_(map0027541873).jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "USFC Steamer Albatross expedition chart, Alexander Agassiz, 1900. Source: NOAA Photo Library. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/albatross-track-1900.webp",
    "width": 2400,
    "height": 1923
  },
  {
    "id": "palau-admiralty-1103",
    "name": "1796 Admiralty chart: Palau (Peeloo) Archipelago",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Palau",
      "Babeldaob",
      "Koror",
      "Micronesia",
      "Pacific",
      "1796",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — John McCluer, published by Alexander Dalrymple",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_1103_Peeloo_archipelago_or_Pellew_Islands,_Published_1796.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_1103_Peeloo_archipelago_or_Pellew_Islands,_Published_1796.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Chart of the Peeloo Archipelago, observations by John McCluer 1793-94, published by Alexander Dalrymple 1796. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/palau-admiralty-1103.webp",
    "width": 2400,
    "height": 1594
  },
  {
    "id": "guam-umatac-bay-1796",
    "name": "1796 chart: Umatac Bay, Guam, with coastal profile views",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "nautical chart",
      "Guam",
      "Guahan",
      "Umatac",
      "Micronesia",
      "Pacific",
      "1796",
      "vintage",
      "engraving",
      "line art",
      "navigational",
      "sailor gift",
      "boat gift",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Officers of the Frigate Astrea, Royal Company of the Philippines",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_1101_Umatac_Bay,_Published_1796.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Admiralty_Chart_No_1101_Umatac_Bay,_Published_1796.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Plan of Umatac Bay, Guam, laid down by officers of the Frigate Astrea from observations of Chevalier Malespina, published 1796. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/guam-umatac-bay-1796.webp",
    "width": 2400,
    "height": 1888
  },
  {
    "id": "marshall-stick-chart",
    "name": "Marshallese wave-navigation stick chart",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "stick chart",
      "Marshallese",
      "Marshall Islands",
      "navigation",
      "wayfinding",
      "wave chart",
      "Micronesia",
      "Pacific",
      "traditional science",
      "boat gift",
      "print decoration",
      "engraving"
    ],
    "license": "CC BY-SA 4.0",
    "source": "Wikimedia Commons — Photo: Wikimedia Commons user Velvet, of a Marshallese stick chart held at the Musée du quai Branly, Paris",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paris_musee_branly_carte_navigation_iles_marshall.JPG",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Paris_musee_branly_carte_navigation_iles_marshall.JPG",
    "licenseId": "CC-BY-SA-4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "attributionRequired": true,
    "attributionText": "Photo by Wikimedia Commons user Velvet, Musée du quai Branly, Paris. CC BY-SA 4.0. Marshallese stick charts (rebbelib/meddo) are traditional wave-navigation instruments, publicly exhibited and celebrated in Marshallese culture (including on RMI postage stamps) — not restricted ceremonial material.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/marshall-stick-chart.webp",
    "width": 2400,
    "height": 2011
  },
  {
    "id": "marshall-majuro-atoll",
    "name": "Map of Majuro Atoll, Marshall Islands",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "atoll diagram",
      "Majuro",
      "Marshall Islands",
      "Micronesia",
      "Pacific",
      "navigational",
      "boat gift",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Unattributed public-domain cartography",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Map_of_Majuro_Atoll.png",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Map_of_Majuro_Atoll.png",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Map of Majuro Atoll. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/marshall-majuro-atoll.webp",
    "width": 637,
    "height": 381
  },
  {
    "id": "nauru-regional-map",
    "name": "Nauru detail map with South Pacific locator",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "Nauru",
      "Micronesia",
      "Pacific",
      "1988",
      "district map",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — U.S. government cartography (1988 base map)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nauru_-_DPLA_-_1c744fa83bc11976202e84294e1e0cf8.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Nauru_-_DPLA_-_1c744fa83bc11976202e84294e1e0cf8.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Nauru detail map, U.S. government base map 800205, 1988. Digital Public Library of America. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/nauru-regional-map.webp",
    "width": 1874,
    "height": 2400
  },
  {
    "id": "kiribati-tarawa-atoll",
    "name": "Tarawa Atoll diagram, Kiribati",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "atoll diagram",
      "Tarawa",
      "Kiribati",
      "Gilbert Islands",
      "Pacific",
      "modern",
      "minimal",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Unattributed public-domain cartography (rendered from SVG source)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tarawa_Atoll,_Kiribati.svg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:Tarawa_Atoll,_Kiribati.svg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Tarawa Atoll diagram. Wikimedia Commons. Public domain. Rendered from the original SVG source.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/kiribati-tarawa-atoll.webp",
    "width": 2400,
    "height": 2400
  },
  {
    "id": "kiribati-south-tarawa",
    "name": "South Tarawa, Kiribati: labeled satellite-style map",
    "kind": "element",
    "category": "Maps & Charts",
    "tags": [
      "map",
      "satellite map",
      "Tarawa",
      "Betio",
      "Bairiki",
      "Kiribati",
      "Gilbert Islands",
      "Pacific",
      "print decoration"
    ],
    "license": "Public domain",
    "source": "Wikimedia Commons — Government of USA / Government of Kiribati",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:06_Map_of_South_Tarawa,_Kiribati.jpg",
    "evidenceUrl": "https://commons.wikimedia.org/wiki/File:06_Map_of_South_Tarawa,_Kiribati.jpg",
    "licenseId": "PD",
    "licenseUrl": "https://en.wikipedia.org/wiki/Public_domain",
    "attributionRequired": false,
    "attributionText": "Map of South Tarawa, Kiribati. Government of USA / Government of Kiribati. Wikimedia Commons. Public domain.",
    "commercialUse": true,
    "modificationAllowed": true,
    "redistributionAllowed": true,
    "imageUrl": "/studio-assets/wikimedia-commons-pacific-charts/kiribati-south-tarawa.webp",
    "width": 1294,
    "height": 509
  }
];
